import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import type Database from "better-sqlite3";
import { RemoteTaskRecordSchema } from "@stackpilot/contracts";
import { AgentNodeStateSchema } from "../repositories/agentControlRepository.js";
import { z } from "zod";

const schema=z.object({enrollments:z.array(z.object({enrollmentId:z.string(),tokenDigest:z.string(),nodeName:z.string(),expiresAt:z.string(),usedAt:z.string().nullable(),revokedAt:z.string().nullable()})),credentials:z.array(z.object({credentialId:z.string(),nodeId:z.string(),publicKey:z.string(),createdAt:z.string(),revokedAt:z.string().nullable(),replacedBy:z.string().nullable(),rotationId:z.string().nullable()})),nodes:z.array(AgentNodeStateSchema),nonces:z.array(z.object({credentialId:z.string(),nonce:z.string(),expiresAt:z.string()})),tasks:z.array(RemoteTaskRecordSchema),audits:z.array(z.object({eventId:z.string(),timestamp:z.string()}).passthrough())});
export async function importLegacyAgentState(database:Database.Database,path:string):Promise<{imported:boolean;digest:string}>{const raw=await readFile(path);const sourceDigest=createHash("sha256").update(raw).digest("hex");if(database.prepare("SELECT 1 FROM legacy_imports WHERE source_path=? AND source_digest=?").get(path,sourceDigest))return{imported:false,digest:sourceDigest};const state=schema.parse(JSON.parse(raw.toString("utf8")));database.transaction(()=>{for(const x of state.enrollments)database.prepare("INSERT OR IGNORE INTO agent_enrollments VALUES(?,?,?,?,?,?)").run(x.enrollmentId,x.tokenDigest,x.nodeName,x.expiresAt,x.usedAt,x.revokedAt);for(const x of state.nodes)database.prepare("INSERT OR IGNORE INTO agent_nodes(node_id,payload,revoked_at,updated_at)VALUES(?,?,?,?)").run(x.nodeId,JSON.stringify(x),x.revokedAt,x.lastSeenAt??x.enrolledAt);for(const x of state.credentials)database.prepare("INSERT OR IGNORE INTO agent_credentials VALUES(?,?,?,?,?,?,?)").run(x.credentialId,x.nodeId,x.publicKey,x.createdAt,x.revokedAt,x.replacedBy,x.rotationId);for(const x of state.nonces)database.prepare("INSERT OR IGNORE INTO agent_nonces VALUES(?,?,?)").run(x.credentialId,x.nonce,x.expiresAt);for(const x of state.tasks)database.prepare("INSERT OR IGNORE INTO remote_tasks(task_id,node_id,payload,status,updated_at)VALUES(?,?,?,?,?)").run(x.taskId,x.targetNodeId,JSON.stringify(x),x.status,x.updatedAt);for(const x of state.audits)database.prepare("INSERT OR IGNORE INTO agent_protocol_audits VALUES(?,?,?)").run(x.eventId,JSON.stringify(x),x.timestamp);database.prepare("INSERT OR REPLACE INTO legacy_imports VALUES(?,?,?)").run(path,sourceDigest,new Date().toISOString());})();return{imported:true,digest:sourceDigest};}
