import { useRef, useState } from "react";
import type { Notify } from "../../types/app";

export function useNotificationSettings(guardWrite: (action: string) => boolean, notify: Notify) {
  const [mailNotice, setMailNotice] = useState(true); const noticeWebhookInputRef = useRef<HTMLInputElement>(null), noticeRecipientsInputRef = useRef<HTMLInputElement>(null);
  const [noticeDraft, setNoticeDraft] = useState({ webhook: "https://hooks.example.com/stackpilot", recipients: "ops@example.com, dev@example.com", severity: "关键与告警", digest: "每小时摘要" });
  const [savedNotice, setSavedNotice] = useState({ ...noticeDraft, mailEnabled: true, events: ["高危告警", "备份失败", "部署完成"] });
  const [noticeErrors, setNoticeErrors] = useState({ webhook: "", recipients: "" });
  const [noticeConnection, setNoticeConnection] = useState({ status: "格式已检查", detail: "通知格式已检查，预计响应 45ms", tone: "ok" as "ok" | "warn" | "error", signature: "https://hooks.example.com/stackpilot::mail::ops@example.com, dev@example.com" });
  const [noticeSavedAt, setNoticeSavedAt] = useState("2025-08-12 18:43"), [noticeEvents, setNoticeEvents] = useState(["高危告警", "备份失败", "部署完成"]);
  const [noticeDeliveries, setNoticeDeliveries] = useState([{ id: "notice-1", time: "18:42", channel: "Webhook", target: "ops-alerts", result: "成功", latency: "45ms" }, { id: "notice-2", time: "18:20", channel: "邮件", target: "ops@example.com", result: "成功", latency: "1.2s" }, { id: "notice-3", time: "17:58", channel: "Webhook", target: "deploy-room", result: "重试中", latency: "3.4s" }]);
  const read = () => ({ ...noticeDraft, webhook: noticeWebhookInputRef.current?.value ?? noticeDraft.webhook, recipients: noticeRecipientsInputRef.current?.value ?? noticeDraft.recipients });
  const signature = (draft: typeof noticeDraft, enabled = mailNotice) => `${draft.webhook.trim()}::${enabled ? `mail::${draft.recipients.trim()}` : "webhook-only"}`;
  const validate = (draft: typeof noticeDraft) => { const recipients = draft.recipients.split(",").map((item) => item.trim()).filter(Boolean); return { webhook: /^https:\/\/[\w.-]+(?::\d+)?(?:\/[\w./?=&:%+-]*)?$/.test(draft.webhook.trim()) ? "" : "请输入 https:// 开头的 Webhook 地址", recipients: !mailNotice || recipients.length > 0 && recipients.every((item) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(item)) ? "" : "请输入有效邮箱，多个收件人用逗号分隔" }; };
  const updateNoticeDraft = (key: keyof typeof noticeDraft, value: string) => { if (!guardWrite("修改通知设置")) return; const next = { ...noticeDraft, [key]: value }; setNoticeDraft(next); setNoticeErrors((current) => ({ ...current, [key]: "" })); setNoticeConnection((current) => key === "webhook" || key === "recipients" && mailNotice ? { status: "待检查", detail: "通知渠道已变更，需要重新检查配置。", tone: "warn", signature: "" } : { ...current, status: "待保存", detail: "通知策略已变更，保存后生效。", tone: "warn" }); };
  const toggleNoticeEvent = (name: string) => { if (!guardWrite("修改通知事件")) return; setNoticeEvents((current) => current.includes(name) ? current.filter((item) => item !== name) : [...current, name]); setNoticeConnection((current) => ({ ...current, status: "待保存", detail: "事件范围已变更，保存后生效。", tone: "warn" })); };
  const testNoticeConnection = () => { if (!guardWrite("检查通知渠道")) return false; const draft = read(), errors = validate(draft); setNoticeDraft(draft); setNoticeErrors(errors); if (errors.webhook || errors.recipients) { setNoticeConnection({ status: "需要检查", detail: errors.webhook || errors.recipients, tone: "error", signature: "" }); notify(errors.webhook ? "Webhook 地址格式不正确" : "通知收件人格式不正确", "danger"); return false; } const latency = `${38 + noticeDeliveries.length * 3}ms`; setNoticeConnection({ status: "格式已检查", detail: `通知格式已检查，预计响应 ${latency}`, tone: "ok", signature: signature(draft) }); notify(`通知渠道检查通过：${latency}`); return true; };
  const ready = (draft: typeof noticeDraft) => { const errors = validate(draft); setNoticeErrors(errors); if (errors.webhook || errors.recipients) { notify(errors.webhook ? "Webhook 地址格式不正确" : "通知收件人格式不正确", "danger"); return false; } if (!noticeEvents.length) { notify("至少选择一个通知事件", "danger"); return false; } if (noticeConnection.signature !== signature(draft) || noticeConnection.tone !== "ok") { setNoticeConnection({ status: "待检查", detail: "请先检查当前通知渠道配置。", tone: "warn", signature: "" }); notify("请先检查当前通知渠道配置", "warning"); return false; } return true; };
  const saveNoticeSettings = () => { if (!guardWrite("保存通知设置")) return; const draft = read(); setNoticeDraft(draft); if (!ready(draft)) return; setNoticeSavedAt("刚刚"); setSavedNotice({ ...draft, mailEnabled: mailNotice, events: noticeEvents }); setNoticeConnection((current) => ({ ...current, status: "格式已检查", detail: "通知策略已保存，配置格式有效。", tone: "ok" })); notify("通知设置已保存"); };
  const sendNoticePreview = () => { if (!guardWrite("发送通知预览")) return; const draft = read(); setNoticeDraft(draft); if (!ready(draft)) return; const recipients = draft.recipients.split(",").map((item) => item.trim()).filter(Boolean); setNoticeDeliveries((current) => [{ id: `notice-preview-${Date.now()}`, time: "刚刚", channel: mailNotice ? "邮件 + Webhook" : "Webhook", target: mailNotice ? recipients[0]! : "ops-alerts", result: "成功", latency: "52ms" }, ...current.slice(0, 4)]); notify("通知预览已发送"); };
  return { mailNotice, setMailNotice, noticeWebhookInputRef, noticeRecipientsInputRef, noticeDraft, setNoticeDraft, savedNotice, noticeErrors, setNoticeErrors, noticeConnection, setNoticeConnection, noticeSavedAt, noticeEvents, noticeDeliveries, noticeSignature: signature, updateNoticeDraft, toggleNoticeEvent, testNoticeConnection, saveNoticeSettings, sendNoticePreview, readNoticeDraft: read };
}
