import { useRef, useState } from "react";
import type { Notify } from "../../types/app";

export function useSecuritySettings(guardWrite: (action: string) => boolean, notify: Notify) {
  const [twoFactor, setTwoFactor] = useState(true), [multiLogin, setMultiLogin] = useState(false);
  const securityWhitelistInputRef = useRef<HTMLInputElement>(null);
  const [securityDraft, setSecurityDraft] = useState({ sessionTimeout: "30 分钟", ipWhitelist: "10.0.0.0/8, 172.16.0.0/12", lockPolicy: "5 次 / 15 分钟" });
  const [securityError, setSecurityError] = useState(""), [securitySavedAt, setSecuritySavedAt] = useState("2025-08-12 18:47");
  const [securityReview, setSecurityReview] = useState("2 个 IP 白名单等待复核"), [securityReviewTone, setSecurityReviewTone] = useState<"ok" | "warn">("warn");
  const updateSecurityDraft = (key: keyof typeof securityDraft, value: string) => { if (!guardWrite("修改安全策略")) return; setSecurityDraft((current) => ({ ...current, [key]: value })); setSecurityError(""); setSecurityReview("安全策略已变更，等待复核"); setSecurityReviewTone("warn"); };
  const validate = (value: string) => { const rows = value.split(",").map((item) => item.trim()).filter(Boolean); if (!rows.length) return "至少保留一个 IP 或 CIDR 白名单"; const valid = rows.every((row) => { const [ip, prefix] = row.split("/"), octets = ip.split("."); return octets.length === 4 && octets.every((part) => /^\d{1,3}$/.test(part) && Number(part) <= 255) && (prefix === undefined || /^\d{1,2}$/.test(prefix) && Number(prefix) <= 32); }); return valid ? "" : "仅支持 IPv4 或 CIDR，例如 10.0.0.0/8"; };
  const review = (value: string) => { const error = validate(value); if (error) return { ok: false, message: error, tone: "warn" as const }; if (!twoFactor) return { ok: false, message: "MFA 未强制启用，建议复核", tone: "warn" as const }; if (multiLogin) return { ok: false, message: "多地登录已开启，等待安全复核", tone: "warn" as const }; return { ok: true, message: "MFA 覆盖率 100%，白名单校验通过", tone: "ok" as const }; };
  const saveSecurityPolicy = () => { if (!guardWrite("保存安全策略")) return; const ipWhitelist = securityWhitelistInputRef.current?.value ?? securityDraft.ipWhitelist; setSecurityDraft((current) => ({ ...current, ipWhitelist })); const error = validate(ipWhitelist); if (error) { setSecurityError(error); notify(error.includes("至少") ? "IP 白名单不能为空" : "IP 白名单格式不正确", "danger"); return; } const result = review(ipWhitelist); setSecuritySavedAt("刚刚"); setSecurityReview(result.ok ? "安全策略已校准" : result.message); setSecurityReviewTone(result.tone); notify("安全策略已保存"); };
  const runSecurityReview = () => { if (!guardWrite("执行安全复核")) return; const ipWhitelist = securityWhitelistInputRef.current?.value ?? securityDraft.ipWhitelist; setSecurityDraft((current) => ({ ...current, ipWhitelist })); const result = review(ipWhitelist); if (!result.ok && validate(ipWhitelist)) setSecurityError(result.message); setSecurityReview(result.message); setSecurityReviewTone(result.tone); notify(result.ok ? "安全策略复核已完成" : "安全策略复核未通过", result.ok ? "success" : "warning"); };
  return { twoFactor, setTwoFactor, multiLogin, setMultiLogin, securityWhitelistInputRef, securityDraft, securityError, securitySavedAt, securityReview, setSecurityReview, securityReviewTone, setSecurityReviewTone, updateSecurityDraft, saveSecurityPolicy, runSecurityReview };
}
