import { CheckCircle2, Clock3, Copy, Eye, Info, Play, Wifi, WifiOff, XCircle } from "lucide-react";
import type { LiveTerminalHistory, LiveTerminalSession } from "./liveTypes";

function LiveStatus({ connected, compact = false }: { connected: boolean; compact?: boolean }) { const Icon = connected ? Wifi : WifiOff; return <span className={`terminal-semantic-status ${connected ? "green" : "gray"} ${compact ? "compact" : ""}`}><Icon size={compact ? 13 : 15} />{connected ? "Agent 在线" : "Agent 离线"}</span>; }
function LiveSessionList({ rows, selectedId, onSelect, onDetail }: { rows: LiveTerminalSession[]; selectedId: string; onSelect: (row: LiveTerminalSession) => void; onDetail: (id: string) => void }) { return <div className="terminal-session-list">{rows.map((session) => <article key={session.id} className={session.id === selectedId ? "active" : ""}><button className="terminal-session-main" type="button" aria-label={`切换终端目标 ${session.host}`} onClick={() => onSelect(session)}><span><LiveStatus connected={session.status === "connected"} compact /><b title={session.host}>{session.host}</b><em>{session.ip}</em></span><strong>{session.user}</strong><p>{session.cwd}</p><small>{session.lastCommand}</small></button><div className="terminal-card-actions"><span>{session.latency}</span><div><button type="button" aria-label={`查看 ${session.host} 目标详情`} onClick={() => onDetail(session.id)}><Info size={14} />详情</button></div></div></article>)}{rows.length === 0 && <p className="module-empty-card">当前授权范围内没有匹配的 Agent 节点</p>}</div>; }
function LiveHistoryList({ rows, onDetail, onCopy, onRun }: { rows: LiveTerminalHistory[]; onDetail: (id: string) => void; onCopy: (value: string) => void; onRun: (row: LiveTerminalHistory) => void }) { return <div className="terminal-history-list">{rows.map((row) => { const Icon = row.status === "成功" ? CheckCircle2 : row.status === "失败" ? XCircle : Clock3; const tone = row.status === "成功" ? "green" : row.status === "失败" ? "red" : "blue"; return <article key={row.id}><header><span className={`terminal-history-status ${tone}`}><Icon size={16} />{row.status}</span></header><button className="terminal-history-command" type="button" aria-label={`查看任务详情 ${row.command}`} onClick={() => onDetail(row.id)}><code>{row.command}</code></button><p className="terminal-history-context"><b title={row.host}>{row.host}</b><span>{row.user} · {row.time} · {row.duration}</span></p><p className="terminal-history-output">{row.output}</p><footer><button className="terminal-history-action" type="button" onClick={() => onDetail(row.id)}><Eye size={15} />详情</button><button className="terminal-history-action" type="button" onClick={() => onCopy(row.command)}><Copy size={15} />复制</button><button className="terminal-history-action" type="button" disabled={row.status === "执行中"} onClick={() => onRun(row)}><Play size={15} />重跑</button></footer></article>; })}{rows.length === 0 && <p className="module-empty-card">没有真实终端任务历史</p>}</div>; }
function LiveConsole({ session, command, logs, busy, canExecute, onCommand, onRun, onDetail, onCopy }: { session: LiveTerminalSession | null; command: string; logs: string[]; busy: boolean; canExecute: boolean; onCommand: (value: string) => void; onRun: () => void; onDetail: () => void; onCopy: () => void }) { const connected = session?.status === "connected"; return <section className="terminal-console-card"><div className="terminal-console-head"><div><span>{session ? `${session.user}@${session.host}` : "等待 Agent 节点"}</span><strong>{session?.cwd ?? "当前授权范围内尚无节点"}</strong></div><div className="terminal-console-head-actions">{session && <><LiveStatus connected={connected} /><button type="button" onClick={onDetail}><Eye size={14} />详情</button></>}</div></div><div className="terminal-panel"><div className="terminal-toolbar">{session ? <LiveStatus connected={connected} compact /> : <span>未选择目标</span>}<div><button type="button" disabled={!logs.length} onClick={onCopy}><Copy size={14} />复制真实输出</button></div></div><div className="terminal-log" role="log" aria-live="polite" aria-label={`${session?.host ?? "终端"} 输出`}>{logs.length ? logs.map((line, index) => <p key={`${index}-${line}`}>{line}</p>) : <p>{session ? "此节点尚无受控终端任务输出" : "等待真实 Agent 节点上线"}</p>}</div><label className="terminal-input"><span>{session ? `${session.host}:~$` : "agent:~$"}</span><input aria-label="命令输入" value={command} disabled={!connected || !canExecute || busy} placeholder={!canExecute ? "当前账号没有任务执行权限" : connected ? "输入受支持的只读命令" : "Agent 离线，暂不可执行"} onChange={(event) => onCommand(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") onRun(); }} /><button type="button" disabled={!connected || !canExecute || busy || !command.trim()} onClick={onRun}>{busy ? "提交中" : "运行"}</button></label></div></section>; }

export { LiveConsole, LiveHistoryList, LiveSessionList };
