import { ApiTokenListResponseSchema, CreateApiTokenRequestSchema, CreateApiTokenResponseSchema, CreateUserRequestSchema, CurrentUserResponseSchema, EmptyObjectSchema, LoginRequestSchema, LoginResponseSchema, PasswordChangeRequestSchema, ReauthenticateRequestSchema, ReauthenticateResponseSchema, RoleListResponseSchema, SessionStatusResponseSchema, UpdateUserAccessRequestSchema, UpsertRoleRequestSchema, UserListResponseSchema } from "@stackpilot/contracts";
import type { RequestContext } from "./types.js";
import { notFound } from "./errors/ApiError.js";
import { clearSessionCookie, sessionCookie } from "./middleware/userAuthentication.js";
import { sendJson } from "./response/json.js";
import { parseSchema } from "./validation.js";
import { requestSource } from "./trustedProxy.js";

const source=(context:RequestContext)=>requestSource(context.request,context.config.trustedProxies);
export async function routeIdentityRequest(context:RequestContext):Promise<void>{
  const {identity,principal}=context;if(!identity)throw new (await import("./errors/ApiError.js")).ApiError(503,"NOT_READY","身份系统未配置");const method=context.request.method??"GET";const path=context.url.pathname;
  if(path==="/api/auth/login"&&method==="POST"){const input=parseSchema(LoginRequestSchema,context.body,"登录请求");const result=await identity.login(input.username,input.password,source(context),context.request.headers["user-agent"]??"");context.response.setHeader("Set-Cookie",sessionCookie(result.sessionToken,context.config.sessionSeconds,context.config.cookieSecure));identity.audit.append({actorType:"user",actorId:result.principal.userId,sessionId:result.principal.id,source:source(context),action:"auth.login",outcome:"success",authorization:"password",requestId:context.requestId});sendJson(context.response,200,{user:result.principal.user,csrfToken:result.csrfToken,expiresAt:result.expiresAt},LoginResponseSchema);return;}
  if(path==="/api/auth/session"&&method==="GET"){sendJson(context.response,200,principal?{authenticated:true,user:principal.user,csrfToken:identity.rotateCsrf(principal)}:{authenticated:false},SessionStatusResponseSchema);return;}
  if(!principal)throw notFound();
  if(path==="/api/auth/me"&&method==="GET"){sendJson(context.response,200,{user:principal.user,csrfToken:identity.rotateCsrf(principal)},CurrentUserResponseSchema);return;}
  if(path==="/api/auth/logout"&&method==="POST"){parseSchema(EmptyObjectSchema,context.body,"请求体");identity.logout(principal);context.response.setHeader("Set-Cookie",clearSessionCookie(context.config.cookieSecure));sendJson(context.response,200,{message:"已退出登录",tone:"success"});return;}
  if(path==="/api/auth/logout-all"&&method==="POST"){parseSchema(EmptyObjectSchema,context.body,"请求体");identity.consumeReauth(principal,typeof context.request.headers["x-reauth-proof"]==="string"?context.request.headers["x-reauth-proof"]:undefined);identity.logoutAll(principal.userId);context.response.setHeader("Set-Cookie",clearSessionCookie(context.config.cookieSecure));sendJson(context.response,200,{message:"所有会话已撤销",tone:"warning"});return;}
  if(path==="/api/auth/reauthenticate"&&method==="POST"){const input=parseSchema(ReauthenticateRequestSchema,context.body,"重新认证");sendJson(context.response,200,await identity.reauthenticate(principal,input.password),ReauthenticateResponseSchema);return;}
  if(path==="/api/auth/password"&&method==="PATCH"){const input=parseSchema(PasswordChangeRequestSchema,context.body,"修改密码");await identity.changePassword(principal,input.currentPassword,input.newPassword);context.response.setHeader("Set-Cookie",clearSessionCookie(context.config.cookieSecure));sendJson(context.response,200,{message:"密码已更新，请重新登录",tone:"warning"});return;}
  if(path==="/api/tokens"&&method==="GET"){identity.require(principal,"tokens:manage");sendJson(context.response,200,{tokens:identity.listApiTokens(principal.userId)},ApiTokenListResponseSchema);return;}
  if(path==="/api/tokens"&&method==="POST"){identity.require(principal,"tokens:manage");const input=parseSchema(CreateApiTokenRequestSchema,context.body,"API Token");identity.consumeReauth(principal,typeof context.request.headers["x-reauth-proof"]==="string"?context.request.headers["x-reauth-proof"]:undefined);sendJson(context.response,201,identity.createApiToken(principal,input),CreateApiTokenResponseSchema);return;}
  if(context.parts[1]==="tokens"&&context.parts.length===3&&method==="DELETE"){identity.require(principal,"tokens:manage");identity.consumeReauth(principal,typeof context.request.headers["x-reauth-proof"]==="string"?context.request.headers["x-reauth-proof"]:undefined);identity.revokeToken(principal.userId,context.parts[2]??"");sendJson(context.response,200,{message:"Token 已撤销",tone:"warning"});return;}
  if(path==="/api/roles"&&method==="GET"){identity.require(principal,"roles:read");sendJson(context.response,200,{roles:identity.listRoles()},RoleListResponseSchema);return;}
  if(path==="/api/roles"&&method==="POST"){identity.require(principal,"roles:manage");identity.consumeReauth(principal,typeof context.request.headers["x-reauth-proof"]==="string"?context.request.headers["x-reauth-proof"]:undefined);const input=parseSchema(UpsertRoleRequestSchema,context.body,"角色");identity.upsertRole(input.id,input.name,input.description,input.permissions);sendJson(context.response,201,{message:"角色已创建",tone:"success"});return;}
  if(context.parts[1]==="roles"&&context.parts.length===3&&method==="PATCH"){identity.require(principal,"roles:manage");identity.consumeReauth(principal,typeof context.request.headers["x-reauth-proof"]==="string"?context.request.headers["x-reauth-proof"]:undefined);const input=parseSchema(UpsertRoleRequestSchema,context.body,"角色");if(input.id!==context.parts[2])throw notFound("角色不存在");identity.upsertRole(input.id,input.name,input.description,input.permissions);sendJson(context.response,200,{message:"角色权限已更新",tone:"success"});return;}
  if(path==="/api/users"&&method==="GET"){identity.require(principal,"users:read");sendJson(context.response,200,{users:identity.listUsers()},UserListResponseSchema);return;}
  if(path==="/api/users"&&method==="POST"){identity.require(principal,"users:manage");identity.consumeReauth(principal,typeof context.request.headers["x-reauth-proof"]==="string"?context.request.headers["x-reauth-proof"]:undefined);const input=parseSchema(CreateUserRequestSchema,context.body,"用户");await identity.createUser(input.username,input.displayName,input.password,input.roleIds,input.nodeScope);sendJson(context.response,201,{message:"用户已创建",tone:"success"});return;}
  if(context.parts[1]==="users"&&context.parts.length===3&&method==="PATCH"){identity.require(principal,"users:manage");identity.consumeReauth(principal,typeof context.request.headers["x-reauth-proof"]==="string"?context.request.headers["x-reauth-proof"]:undefined);const input=parseSchema(UpdateUserAccessRequestSchema,context.body,"用户权限");identity.updateUserAccess(context.parts[2]??"",input.roleIds,input.nodeScope,input.disabled);sendJson(context.response,200,{message:"用户权限已更新",tone:"success"});return;}
  if(path==="/api/audit"&&method==="GET"){identity.require(principal,"audit:read");sendJson(context.response,200,{events:identity.audit.list()});return;}
  throw notFound("身份接口不存在");
}
