import type { IncomingMessage, ServerResponse } from "node:http";
import type { ControllerConfig } from "../config/environment.js";
import type { Logger } from "../logging/logger.js";
import type { OverviewService } from "../modules/overview/overviewService.js";
import type { RiskService } from "../modules/risks/riskService.js";
import type { ScheduleService } from "../modules/schedules/scheduleService.js";
import type { TaskService } from "../modules/tasks/taskService.js";
import type { EnrollmentService } from "../modules/enrollments/enrollmentService.js";
import type { NodeService } from "../modules/nodes/nodeService.js";
import type { HostMonitoringService } from "../modules/hosts/hostMonitoringService.js";
import type { SiteMonitoringService } from "../modules/sites/siteMonitoringService.js";
import type { CertificateRenewalService } from "../modules/sites/certificateRenewalService.js";
import type { DatabaseMonitoringService } from "../modules/databases/databaseMonitoringService.js";
import type { DatabaseBackupService } from "../modules/databases/databaseBackupService.js";
import type { RemoteTaskService } from "../modules/remote-tasks/remoteTaskService.js";
import type { TerminalSnippetService } from "../modules/terminal/terminalSnippetService.js";
import type { FileService } from "../modules/files/fileService.js";
import type { FileUploadService } from "../modules/files/fileUploadService.js";
import type { DatabaseSlowQueryService } from "../modules/databases/databaseSlowQueryService.js";
import type { DatabaseInventoryService } from "../modules/databases/databaseInventoryService.js";
import type { DatabaseBackupWorkspaceService } from "../modules/databases/databaseBackupWorkspaceService.js";
import type { DatabaseOperationService } from "../modules/databases/databaseOperationService.js";
import type { PlatformAdapter } from "../platform/types.js";
import type { IdentityService } from "../identity/identityService.js";
import type { Principal } from "../identity/types.js";

export type Services = {
  overview: OverviewService;
  hosts: HostMonitoringService;
  databaseInstances: DatabaseMonitoringService;
  databaseSlowQueries: DatabaseSlowQueryService;
  databaseInventory?: DatabaseInventoryService;
  databaseWorkspace?: DatabaseBackupWorkspaceService;
  databaseOperations?: DatabaseOperationService;
  sites: SiteMonitoringService;
  certificateRenewals: CertificateRenewalService;
  databaseBackups: DatabaseBackupService;
  files: FileService;
  fileUploads?: FileUploadService;
  risks: RiskService;
  schedules: ScheduleService;
  tasks: TaskService;
  enrollments: EnrollmentService;
  nodes: NodeService;
  remoteTasks: RemoteTaskService;
  terminalSnippets: TerminalSnippetService;
};
export type RequestContext = {
  request: IncomingMessage;
  response: ServerResponse;
  requestId: string;
  url: URL;
  parts: string[];
  config: ControllerConfig;
  services: Services;
  platform: PlatformAdapter;
  logger: Logger;
  body: unknown;
  rawBody: Buffer;
  identity: IdentityService | null;
  principal?: Principal;
  agentIdentity?: { nodeId: string; credentialId: string };
};
