import type { IncomingMessage, ServerResponse } from "node:http";
import type { ControllerConfig } from "../config/environment.js";
import type { Logger } from "../logging/logger.js";
import type { OverviewService } from "../modules/overview/overviewService.js";
import type { RiskService } from "../modules/risks/riskService.js";
import type { ScheduleService } from "../modules/schedules/scheduleService.js";
import type { TaskService } from "../modules/tasks/taskService.js";
import type { EnrollmentService } from "../modules/enrollments/enrollmentService.js";
import type { NodeService } from "../modules/nodes/nodeService.js";
import type { HostMonitoringService } from "../modules/hosts/hostMonitoringService.js";
import type { SiteMonitoringService } from "../modules/sites/siteMonitoringService.js";
import type { DatabaseBackupService } from "../modules/databases/databaseBackupService.js";
import type { RemoteTaskService } from "../modules/remote-tasks/remoteTaskService.js";
import type { FileUploadService } from "../modules/files/fileUploadService.js";
import type { DatabaseSlowQueryService } from "../modules/databases/databaseSlowQueryService.js";
import type { PlatformAdapter } from "../platform/types.js";
import type { IdentityService } from "../identity/identityService.js";
import type { Principal } from "../identity/types.js";

export type Services = { overview: OverviewService; hosts: HostMonitoringService; databases: DatabaseSlowQueryService; sites: SiteMonitoringService; databaseBackups: DatabaseBackupService; risks: RiskService; schedules: ScheduleService; tasks: TaskService; enrollments: EnrollmentService; nodes: NodeService; remoteTasks: RemoteTaskService; files?: FileUploadService };
export type RequestContext = {
  request: IncomingMessage;
  response: ServerResponse;
  requestId: string;
  url: URL;
  parts: string[];
  config: ControllerConfig;
  services: Services;
  platform: PlatformAdapter;
  logger: Logger;
  body: unknown;
  rawBody: Buffer;
  identity: IdentityService | null;
  principal?: Principal;
  agentIdentity?: { nodeId: string; credentialId: string };
};
