import { createHash } from "node:crypto";import { execFileSync } from "node:child_process";import { mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync, cpSync } from "node:fs";import { dirname,join,resolve } from "node:path";import { fileURLToPath } from "node:url";import { create } from "tar";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"../..");const pkg=JSON.parse(readFileSync(join(root,"package.json"),"utf8"));const version=pkg.version;const out=join(root,"output","release",version);rmSync(out,{recursive:true,force:true});mkdirSync(out,{recursive:true});
const npmCli=process.env.npm_execpath;if(!npmCli)throw new Error("必须通过 npm run release:build 生成制品");const cyclonedx=resolve(root,"node_modules","@cyclonedx","cyclonedx-npm","bin","cyclonedx-npm-cli.js");
execFileSync(process.execPath,[npmCli,"run","build"],{cwd:root,stdio:"inherit"});
execFileSync(process.execPath,[cyclonedx,"--output-file",join(out,"stackpilot-sbom.cdx.json"),"--omit","dev"],{cwd:root,stdio:"inherit"});
const lock=JSON.parse(readFileSync(join(root,"package-lock.json"),"utf8"));const thirdParty=Object.entries(lock.packages).filter(([path,entry])=>path.startsWith("node_modules/")&&!entry.dev&&!entry.link).map(([path,entry])=>({name:path.replace(/^node_modules\//,""),version:entry.version,license:entry.license??"UNKNOWN",resolved:entry.resolved??null,integrity:entry.integrity??null})).sort((a,b)=>a.name.localeCompare(b.name));writeFileSync(join(out,"third-party-packages.json"),`${JSON.stringify(thirdParty,null,2)}\n`);
const stage=join(out,"stage");mkdirSync(stage);for(const path of ["apps/controller/dist","apps/controller/package.json","apps/agent/dist","apps/agent/package.json","apps/cert-helper/dist","apps/cert-helper/package.json","apps/web/dist","apps/web/package.json","packages/contracts/dist","packages/contracts/package.json","packages/host-telemetry/dist","packages/host-telemetry/package.json","packages/config/src","packages/config/package.json","deploy","docs","CHANGELOG.md","README.md","SECURITY.md","LICENSE","package.json","package-lock.json"]){const source=join(root,path);cpSync(source,join(stage,path),{recursive:true});}
const files=[];const walk=(directory,prefix="")=>{for(const name of readdirSync(directory).sort()){const path=join(directory,name);const relative=join(prefix,name).replaceAll("\\","/");if(statSync(path).isDirectory())walk(path,relative);else files.push(relative);}};walk(stage);
const epoch=Number(process.env.SOURCE_DATE_EPOCH??"0");const artifact=join(out,`stackpilot-${version}.tar.gz`);await create({cwd:stage,gzip:true,file:artifact,portable:true,mtime:new Date(epoch*1000),prefix:`stackpilot-${version}`},files);rmSync(stage,{recursive:true,force:true});
const commit=process.env.GITHUB_SHA??execFileSync("git",["rev-parse","HEAD"],{cwd:root,encoding:"utf8"}).trim();const dirty=execFileSync("git",["status","--porcelain"],{cwd:root,encoding:"utf8"}).trim().length>0;const provenance={name:"StackPilot",version,commit,dirty,sourceDateEpoch:epoch,node:process.version,protocol:"1.0",schema:6};writeFileSync(join(out,"provenance.json"),`${JSON.stringify(provenance,null,2)}\n`);
const checksumFiles=readdirSync(out).filter(name=>name!=="SHA256SUMS"&&statSync(join(out,name)).isFile()).sort();writeFileSync(join(out,"SHA256SUMS"),checksumFiles.map(name=>`${createHash("sha256").update(readFileSync(join(out,name))).digest("hex")}  ${name}`).join("\n")+"\n");writeFileSync(join(out,"SIGNING_REQUIRED.txt"),"No signature was created locally. Official releases must be signed by the OIDC keyless Cosign release workflow and verified against the repository identity.\n");process.stdout.write(`${out}\n`);
