import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read=(path)=>readFile(new URL(`../../${path}`,import.meta.url),"utf8");
test("container definitions are pinned, multi-stage and non-root",async()=>{for(const name of ["web","controller","agent"]){const source=await read(`deploy/docker/Dockerfile.${name}`);assert.match(source,/FROM (?:node:22\.22\.0-bookworm-slim|nginx:1\.28\.0-alpine3\.21)/);assert.match(source,/USER \d+:/);assert.doesNotMatch(source,/FROM .*:latest|USER root|--privileged/);if(name!=="web"){assert.match(source,/tini=0\.19\.0-1\+b3/);assert.match(source,new RegExp(`/src/apps/${name}/dist`));assert.doesNotMatch(source,new RegExp(`/src/apps/${name} \\./apps/${name}`));}} });
test("compose exposes only HTTPS and loopback Agent TLS with hardened filesystems",async()=>{const source=await read("deploy/docker/compose.yaml");assert.match(source,/0\.0\.0\.0}:443:8443/);assert.match(source,/127\.0\.0\.1}:9443:9443/);assert.doesNotMatch(source,/8787:8787|privileged:|network_mode:\s*host|\/var\/run\/docker\.sock/);assert.match(source,/profiles: \["agent"\]/);assert.match(source,/STACKPILOT_AGENT_ENROLLMENT_TOKEN_FILE: \/run\/secrets\/agent-enrollment-token/);assert.match(source,/read_only: true/);assert.match(source,/cap_drop: \[ALL\]/);assert.match(source,/internal: true/);assert.doesNotMatch(source,/tmpfs:\s*\[/);assert.match(source,/- \/tmp:size=16m,uid=10001,gid=10001,mode=0700/);assert.match(source,/- \/tmp:size=8m,uid=10002,gid=10002,mode=0700/);});
test("systemd units run separate users with Node-compatible hardening",async()=>{const controller=await read("deploy/systemd/stackpilot-controller.service");const agent=await read("deploy/systemd/stackpilot-agent.service");for(const source of [controller,agent]){assert.match(source,/User=stackpilot-/);assert.match(source,/NoNewPrivileges=yes/);assert.match(source,/ProtectSystem=strict/);assert.match(source,/ProtectProc=invisible/);assert.match(source,/CapabilityBoundingSet=\n/);assert.match(source,/MemoryDenyWriteExecute=no/);assert.doesNotMatch(source,/ProcSubset=pid|User=root|AmbientCapabilities=CAP_/);}assert.match(controller,/ExecStart=\/usr\/bin\/node --preserve-symlinks-main \/opt\/stackpilot\/current\/apps\/controller\/dist\/server\.js/);assert.notEqual(controller.match(/User=(.+)/)?.[1],agent.match(/User=(.+)/)?.[1]);});
test("CI resolves systemd sysusers files from the checkout root",async()=>{const source=await read(".github/workflows/ci.yml");assert.match(source,/systemd-sysusers "\$PWD\/deploy\/systemd\/stackpilot-controller\.sysusers"/);assert.match(source,/systemd-sysusers "\$PWD\/deploy\/systemd\/stackpilot-agent\.sysusers"/);});
test("CI verifies production units against the runner Node executable",async()=>{const source=await read(".github/workflows/ci.yml");assert.match(source,/ln -sf "\$\(command -v node\)" \/usr\/bin\/node\n\s+systemd-analyze verify/);});
test("reverse proxy enforces TLS and security headers",async()=>{for(const path of ["deploy/nginx/container.conf","deploy/nginx/stackpilot.conf.example"]){const source=await read(path);assert.match(source,/ssl_protocols TLSv1\.2 TLSv1\.3/);assert.match(source,/Strict-Transport-Security/);assert.match(source,/Content-Security-Policy/);assert.match(source,/font-src 'self' data:/);assert.match(source,/script-src 'self' 'sha256-\/IiHTQllMEt1knsqzjwvVGxsMxXaQ7ZdISgkRO6D6NI='/);assert.match(source,/client_max_body_size 64k/);assert.match(source,/proxy_set_header Upgrade/);}});
test("production E2E proxy matches the deployed web CSP",async()=>{const source=await read("tests/e2e/support/production-server.mjs");assert.match(source,/font-src 'self' data:/);assert.match(source,/script-src 'self' 'sha256-\/IiHTQllMEt1knsqzjwvVGxsMxXaQ7ZdISgkRO6D6NI='/);});
