import { constants } from "node:fs";
import { access, chmod, lstat, mkdir, readFile, readdir, realpath, rename, rm, writeFile } from "node:fs/promises";
import { basename, dirname, isAbsolute, join, normalize, relative, resolve, sep } from "node:path";
import { createHash, randomUUID } from "node:crypto";
import type { FileEntry, FileListPayload } from "@stackpilot/contracts";
import { ServiceError } from "../serviceError.js";

type RootMatch = { configuredRoot: string; realRoot: string; absolutePath: string };
const isInside = (root: string, candidate: string) => { const value = relative(root, candidate); return value === "" || (value !== ".." && !value.startsWith(`..${sep}`)); };
function validName(value: string) { const name = value.trim(),control=[...name].some((character)=>character.charCodeAt(0)<32); if (!name || name === "." || name === ".." || name === ".stackpilot-trash" || /[\\/]/.test(name) || control) throw new ServiceError(400,"BAD_REQUEST","文件名无效"); return name; }

export class FileService {
  private owners: Map<number, string> | null = null;
  private mutation = Promise.resolve();
  constructor(private readonly roots: readonly string[]) { if (!roots.length || roots.some((root) => !isAbsolute(root))) throw new Error("文件根目录必须是绝对路径"); }
  private async mutate<T>(operation:()=>Promise<T>):Promise<T>{const previous=this.mutation;let release!:()=>void;this.mutation=new Promise<void>((resolve)=>{release=resolve;});await previous;try{return await operation();}finally{release();}}
  private normalized(value: string) { if (!isAbsolute(value) || value.includes("\0")) throw new ServiceError(400,"BAD_REQUEST","文件路径无效");const path=normalize(value);if(path.split(sep).includes(".stackpilot-trash"))throw new ServiceError(403,"FORBIDDEN","文件回收目录不可直接访问");return path; }
  private async rootFor(path: string) { const matches=await Promise.all(this.roots.map(async(item)=>{const configuredRoot=resolve(item);try{const realRoot=await realpath(configuredRoot);return isInside(configuredRoot,path)||isInside(realRoot,path)?{configuredRoot,realRoot}:null;}catch{return null;}}));const root=matches.filter((item):item is {configuredRoot:string;realRoot:string}=>Boolean(item)).sort((a,b)=>b.realRoot.length-a.realRoot.length)[0];if(!root)throw new ServiceError(403,"FORBIDDEN","文件路径超出允许范围");return root; }
  private async existing(value: string): Promise<RootMatch> {
    const absolutePath=this.normalized(value),{configuredRoot,realRoot}=await this.rootFor(absolutePath);let realTarget:string;
    try{realTarget=await realpath(absolutePath);}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")throw new ServiceError(404,"NOT_FOUND","文件或目录不存在");throw error;}
    const base=isInside(configuredRoot,absolutePath)?configuredRoot:realRoot,expected=join(realRoot,relative(base,absolutePath));if(!isInside(realRoot,realTarget)||realTarget!==expected)throw new ServiceError(403,"FORBIDDEN","文件路径包含不受信任的符号链接");return{configuredRoot,realRoot,absolutePath:realTarget};
  }
  private async targetForNew(path:string){const parent=await this.existing(dirname(path)),target=join(parent.absolutePath,basename(path));if(!isInside(parent.realRoot,target))throw new ServiceError(403,"FORBIDDEN","文件路径超出允许范围");return target;}
  private async owner(uid:number){if(!this.owners){this.owners=new Map();try{for(const line of (await readFile("/etc/passwd","utf8")).split("\n")){const row=line.split(":"),id=Number(row[2]);if(row[0]&&Number.isInteger(id))this.owners.set(id,row[0]);}}catch{/* Numeric UID fallback. */}}return this.owners.get(uid)??`UID ${uid}`;}
  private async entry(path:string,parentPath=dirname(path)):Promise<FileEntry>{const stats=await lstat(path),kind=stats.isDirectory()?"directory":stats.isSymbolicLink()?"symlink":"file";return{id:createHash("sha256").update(path).digest("hex"),name:basename(path),kind,path,parentPath,sizeBytes:kind==="file"?stats.size:null,modifiedAt:stats.mtime.toISOString(),owner:await this.owner(stats.uid)};}
  async list(value:string):Promise<FileListPayload>{const match=await this.existing(value),stats=await lstat(match.absolutePath);if(!stats.isDirectory())throw new ServiceError(400,"BAD_REQUEST","请求路径不是目录");const names=(await readdir(match.absolutePath)).filter((name)=>name!==".stackpilot-trash");if(names.length>5000)throw new ServiceError(413,"PAYLOAD_TOO_LARGE","目录项目超过 5000 个");const entries=await Promise.all(names.map((name)=>this.entry(join(match.absolutePath,name),match.absolutePath)));entries.sort((a,b)=>a.kind===b.kind?a.name.localeCompare(b.name):a.kind==="directory"?-1:1);return{rootPath:match.configuredRoot,path:match.absolutePath,parentPath:match.absolutePath===match.realRoot?null:dirname(match.absolutePath),entries,collectedAt:new Date().toISOString(),writable:await access(match.absolutePath,constants.W_OK).then(()=>true,()=>false)};}
  async createDirectory(path:string,name:string){return this.mutate(async()=>{const parent=await this.existing(path),target=join(parent.absolutePath,validName(name));if(!isInside(parent.realRoot,target))throw new ServiceError(403,"FORBIDDEN","文件路径超出允许范围");try{await mkdir(target,{mode:0o775});}catch(error){if((error as NodeJS.ErrnoException).code==="EEXIST")throw new ServiceError(409,"BAD_REQUEST","同名项目已存在");throw error;}await chmod(target,0o775);return this.entry(target,parent.absolutePath);});}
  async upload(path:string,name:string,content:Buffer){return this.mutate(async()=>{const target=await this.targetForNew(join(this.normalized(path),validName(name)));try{await writeFile(target,content,{flag:"wx",mode:0o664});}catch(error){if((error as NodeJS.ErrnoException).code==="EEXIST")throw new ServiceError(409,"BAD_REQUEST","同名项目已存在");throw error;}await chmod(target,0o664);return this.entry(target,dirname(target));});}
  async rename(path:string,newName:string){return this.mutate(async()=>{const source=await this.existing(path);if(source.absolutePath===source.realRoot)throw new ServiceError(403,"FORBIDDEN","不能重命名文件根目录");const target=await this.targetForNew(join(dirname(source.absolutePath),validName(newName)));try{await lstat(target);throw new ServiceError(409,"BAD_REQUEST","同名项目已存在");}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}await rename(source.absolutePath,target);return this.entry(target,dirname(target));});}
  async moveToTrash(path:string){return this.mutate(async()=>{const source=await this.existing(path);if(source.absolutePath===source.realRoot)throw new ServiceError(403,"FORBIDDEN","不能删除文件根目录");const trash=join(source.realRoot,".stackpilot-trash");try{const stats=await lstat(trash);if(!stats.isDirectory()||stats.isSymbolicLink())throw new ServiceError(403,"FORBIDDEN","文件回收目录不安全");}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;await mkdir(trash,{mode:0o700});}const bucket=join(trash,randomUUID());await mkdir(bucket,{mode:0o700});try{await rename(source.absolutePath,join(bucket,basename(source.absolutePath)));}catch(error){await rm(bucket,{recursive:true,force:true});throw error;}return basename(source.absolutePath);});}
}
