import { Algorithm, hash, verify } from "@node-rs/argon2";
import type { ApiTokenRecord, CreateApiTokenRequest, NodeScope, Permission, PublicUser } from "@stackpilot/contracts";
import type Database from "better-sqlite3";
import { randomUUID } from "node:crypto";
import { AuditRepository } from "../audit/auditRepository.js";
import { ServiceError } from "../modules/serviceError.js";
import { constantTimeDigestEqual, digest, randomToken } from "../security/crypto.js";
import type { Principal } from "./types.js";

const argon = { algorithm: Algorithm.Argon2id, memoryCost: 19_456, timeCost: 2, parallelism: 1, outputLen: 32 } as const;
export const PERMISSIONS: ReadonlyArray<[Permission, "low" | "medium" | "high", string]> = [
  ["overview:read","low","读取本机总览"],["overview:operate","medium","执行本机操作"],["schedules:read","low","读取定时任务"],["schedules:write","high","修改定时任务"],
  ["nodes:read","low","读取授权节点"],["nodes:manage","high","注册、轮换或撤销节点"],["tasks:read","low","读取远程任务"],["tasks:create","high","创建远程任务"],["tasks:cancel","medium","取消远程任务"],
  ["databases:read","low","读取授权节点的数据库实例"],
  ["files:read","low","读取上传任务"],["files:write","high","创建和管理文件上传"],
  ["audit:read","low","读取审计日志"],["users:read","low","读取用户"],["users:manage","high","管理用户"],["roles:read","low","读取角色"],["roles:manage","high","管理角色"],["tokens:manage","high","管理 API Token"],["system:backup","high","备份与恢复数据库"],
];
const roleDefinitions = [
  ["administrator","管理员",PERMISSIONS.map(([key]) => key)],
  ["operator","运维人员",["overview:read","overview:operate","schedules:read","schedules:write","nodes:read","databases:read","files:read","files:write","tasks:read","tasks:create","tasks:cancel"]],
  ["audit-reader","只读审计员",["overview:read","nodes:read","databases:read","tasks:read","audit:read"]],
] as const;

type UserRow = { id: string; username: string; display_name: string; password_hash: string; disabled_at: string | null };
export class IdentityService {
  readonly audit: AuditRepository;
  private readonly dummyHashPromise = hash("stackpilot-dummy-password-not-a-credential", argon);
  constructor(private readonly database: Database.Database, auditKey: Buffer, private readonly sessionSeconds = 43_200) { this.audit = new AuditRepository(database, auditKey); this.seedRbac(); }
  private seedRbac() {
    this.database.transaction(() => {
      const permission = this.database.prepare("INSERT OR IGNORE INTO permissions(key,risk,description) VALUES(?,?,?)");
      for (const entry of PERMISSIONS) permission.run(...entry);
      const role = this.database.prepare("INSERT OR IGNORE INTO roles(id,name,description,builtin,created_at) VALUES(?,?,?,?,?)");
      const mapping = this.database.prepare("INSERT OR IGNORE INTO role_permissions(role_id,permission_key) VALUES(?,?)");
      for (const [id, name, permissions] of roleDefinitions) { role.run(id, name, `${name}内置角色`, 1, new Date().toISOString()); for (const key of permissions) mapping.run(id, key); }
    })();
  }
  hasAdministrator(): boolean { return Boolean(this.database.prepare("SELECT 1 FROM user_roles WHERE role_id='administrator' LIMIT 1").get()); }
  validatePassword(password: string) { if (password.length < 12 || password.length > 128) throw new ServiceError(400,"BAD_REQUEST","密码长度必须为 12 至 128 个字符"); }
  async createInitialAdministrator(username: string, displayName: string, password: string): Promise<string> {
    this.validatePassword(password); const passwordHash = await hash(password, argon); const id = randomUUID(); const now = new Date().toISOString();
    try { this.database.transaction(() => { if (this.hasAdministrator()) throw new ServiceError(409,"BAD_REQUEST","系统已经完成初始化"); this.database.prepare("INSERT INTO users(id,username,password_hash,display_name,password_changed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(id,username,passwordHash,displayName,now,now,now); this.database.prepare("INSERT INTO user_roles(user_id,role_id) VALUES(?,'administrator')").run(id); })(); }
    catch (error) { if (String(error).includes("UNIQUE")) throw new ServiceError(409,"BAD_REQUEST","系统已经完成初始化"); throw error; }
    return id;
  }
  private publicUser(row: UserRow): PublicUser {
    const permissions = (this.database.prepare("SELECT DISTINCT rp.permission_key AS key FROM user_roles ur JOIN role_permissions rp ON rp.role_id=ur.role_id WHERE ur.user_id=?").all(row.id) as Array<{key: Permission}>).map((item)=>item.key);
    const roles = (this.database.prepare("SELECT role_id AS id FROM user_roles WHERE user_id=?").all(row.id) as Array<{id:string}>).map((item)=>item.id);
    const scopes = (this.database.prepare("SELECT node_id AS id FROM user_node_scopes WHERE user_id=?").all(row.id) as Array<{id:string}>).map((item)=>item.id);
    return { id: row.id, username: row.username, displayName: row.display_name, permissions, roles, nodeScope: roles.includes("administrator") ? "all" : scopes };
  }
  private userById(id: string) { return this.database.prepare("SELECT * FROM users WHERE id=?").get(id) as UserRow | undefined; }
  private bucket(username: string, source: string) { return digest(`${username.toLocaleLowerCase()}\0${source}`); }
  private rateCheck(bucket: string) { const row = this.database.prepare("SELECT failures,blocked_until FROM login_attempts WHERE bucket_digest=?").get(bucket) as {failures:number;blocked_until:string|null}|undefined; if (row?.blocked_until && Date.parse(row.blocked_until)>Date.now()) throw new ServiceError(429,"TOO_MANY_REQUESTS","尝试过于频繁，请稍后重试"); }
  private rateFailure(bucket: string) { const row=this.database.prepare("SELECT failures FROM login_attempts WHERE bucket_digest=?").get(bucket) as {failures:number}|undefined; const failures=(row?.failures??0)+1; const seconds=Math.min(300, failures<3?0:2**Math.min(failures-3,8)); const now=new Date().toISOString(); const blocked=seconds?new Date(Date.now()+seconds*1000).toISOString():null; this.database.prepare("INSERT INTO login_attempts(bucket_digest,failures,blocked_until,updated_at) VALUES(?,?,?,?) ON CONFLICT(bucket_digest) DO UPDATE SET failures=excluded.failures,blocked_until=excluded.blocked_until,updated_at=excluded.updated_at").run(bucket,failures,blocked,now); }
  async login(username: string, password: string, source: string, userAgent: string): Promise<{ principal: Principal; sessionToken:string; csrfToken:string; expiresAt:string }> {
    const bucket=this.bucket(username,source); this.rateCheck(bucket); const row=this.database.prepare("SELECT * FROM users WHERE username=? COLLATE NOCASE").get(username) as UserRow|undefined; const passwordHash=row?.password_hash??await this.dummyHashPromise; const valid=await verify(passwordHash,password).catch(()=>false);
    if(!row||row.disabled_at||!valid){this.rateFailure(bucket);throw new ServiceError(401,"UNAUTHORIZED","用户名或密码无效");}
    this.database.prepare("DELETE FROM login_attempts WHERE bucket_digest=?").run(bucket); const sessionToken=randomToken(); const csrfToken=randomToken(); const expiresAt=new Date(Date.now()+this.sessionSeconds*1000).toISOString(); const now=new Date().toISOString();
    this.database.prepare("INSERT INTO sessions(id_digest,user_id,csrf_digest,created_at,last_seen_at,expires_at,source,user_agent_hash) VALUES(?,?,?,?,?,?,?,?)").run(digest(sessionToken),row.id,digest(csrfToken),now,now,expiresAt,source,digest(userAgent));
    return { principal:this.principalForUser(row,"session",digest(sessionToken),digest(csrfToken)),sessionToken,csrfToken,expiresAt };
  }
  private principalForUser(row: UserRow,type:"session"|"api-token",id:string,csrfDigest?:string):Principal { const user=this.publicUser(row); return {type,id,userId:row.id,user,permissions:new Set(user.permissions),nodeScope:user.nodeScope,...(csrfDigest?{csrfDigest}:{})}; }
  authenticateSession(token:string):Principal|null { const idDigest=digest(token); const session=this.database.prepare("SELECT * FROM sessions WHERE id_digest=? AND revoked_at IS NULL AND expires_at>?").get(idDigest,new Date().toISOString()) as {user_id:string;csrf_digest:string}|undefined; if(!session)return null; const user=this.userById(session.user_id); if(!user||user.disabled_at)return null; this.database.prepare("UPDATE sessions SET last_seen_at=? WHERE id_digest=?").run(new Date().toISOString(),idDigest); return this.principalForUser(user,"session",idDigest,session.csrf_digest); }
  rotateCsrf(principal:Principal):string { if(principal.type!=="session")return "api-token-authentication".padEnd(32,"_");const token=randomToken();this.database.prepare("UPDATE sessions SET csrf_digest=? WHERE id_digest=? AND revoked_at IS NULL").run(digest(token),principal.id);principal.csrfDigest=digest(token);return token; }
  authenticateApiToken(token:string):Principal|null { const tokenDigest=digest(token); const row=this.database.prepare("SELECT * FROM api_tokens WHERE token_digest=? AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>?)").get(tokenDigest,new Date().toISOString()) as {id:string;user_id:string;all_nodes:number}|undefined; if(!row||!constantTimeDigestEqual(token,tokenDigest))return null; const user=this.userById(row.user_id); if(!user||user.disabled_at)return null; const userPrincipal=this.principalForUser(user,"api-token",row.id); const allowed=new Set((this.database.prepare("SELECT permission_key AS key FROM api_token_permissions WHERE token_id=?").all(row.id) as Array<{key:Permission}>).map(x=>x.key).filter(x=>userPrincipal.permissions.has(x))); const tokenScopes=(this.database.prepare("SELECT node_id AS id FROM api_token_node_scopes WHERE token_id=?").all(row.id) as Array<{id:string}>).map(x=>x.id); const nodeScope:NodeScope=row.all_nodes&&userPrincipal.nodeScope==="all"?"all":userPrincipal.nodeScope==="all"?tokenScopes:(tokenScopes.filter(id=>userPrincipal.nodeScope.includes(id))); this.database.prepare("UPDATE api_tokens SET last_used_at=? WHERE id=?").run(new Date().toISOString(),row.id); return {...userPrincipal,id:row.id,permissions:allowed,nodeScope}; }
  logout(principal:Principal){if(principal.type==="session")this.database.prepare("UPDATE sessions SET revoked_at=? WHERE id_digest=?").run(new Date().toISOString(),principal.id);}
  logoutAll(userId:string){this.database.prepare("UPDATE sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL").run(new Date().toISOString(),userId);}
  verifyCsrf(principal:Principal,csrf:string){if(principal.type!=="session"||!principal.csrfDigest||!constantTimeDigestEqual(csrf,principal.csrfDigest))throw new ServiceError(403,"FORBIDDEN","CSRF 校验失败");}
  require(principal:Principal|undefined,permission:Permission,nodeId?:string){if(!principal)throw new ServiceError(401,"UNAUTHORIZED","需要登录");if(!principal.permissions.has(permission))throw new ServiceError(403,"FORBIDDEN","权限不足");if(nodeId&&principal.nodeScope!=="all"&&!principal.nodeScope.includes(nodeId))throw new ServiceError(403,"FORBIDDEN","节点超出授权范围");}
  async reauthenticate(principal:Principal,password:string){const bucket=this.bucket(`reauth:${principal.userId}`,principal.id);this.rateCheck(bucket);const user=this.userById(principal.userId);if(!user||!await verify(user.password_hash,password)){this.rateFailure(bucket);throw new ServiceError(401,"UNAUTHORIZED","重新认证失败");}this.database.prepare("DELETE FROM login_attempts WHERE bucket_digest=?").run(bucket);const proof=randomToken();const expiresAt=new Date(Date.now()+5*60_000).toISOString();this.database.prepare("INSERT INTO reauth_challenges(digest,user_id,session_digest,expires_at) VALUES(?,?,?,?)").run(digest(proof),principal.userId,principal.id,expiresAt);return{proof,expiresAt};}
  consumeReauth(principal:Principal,proof:string|undefined){if(principal.type!=="session"||!proof)throw new ServiceError(403,"FORBIDDEN","该操作需要重新认证");const proofDigest=digest(proof);const row=this.database.prepare("SELECT digest FROM reauth_challenges WHERE digest=? AND user_id=? AND session_digest=? AND used_at IS NULL AND expires_at>?").get(proofDigest,principal.userId,principal.id,new Date().toISOString());if(!row||!constantTimeDigestEqual(proof,proofDigest))throw new ServiceError(403,"FORBIDDEN","重新认证证明无效或已过期");this.database.prepare("UPDATE reauth_challenges SET used_at=? WHERE digest=?").run(new Date().toISOString(),proofDigest);}
  async changePassword(principal:Principal,current:string,next:string){this.validatePassword(next);const bucket=this.bucket(`password-change:${principal.userId}`,principal.id);this.rateCheck(bucket);const user=this.userById(principal.userId);if(!user||!await verify(user.password_hash,current)){this.rateFailure(bucket);throw new ServiceError(401,"UNAUTHORIZED","当前密码无效");}this.database.prepare("DELETE FROM login_attempts WHERE bucket_digest=?").run(bucket);const passwordHash=await hash(next,argon);this.database.transaction(()=>{this.database.prepare("UPDATE users SET password_hash=?,password_changed_at=?,updated_at=?,version=version+1 WHERE id=?").run(passwordHash,new Date().toISOString(),new Date().toISOString(),principal.userId);this.logoutAll(principal.userId);})();}
  createApiToken(principal:Principal,input:CreateApiTokenRequest):{token:string;record:ApiTokenRecord}{for(const permission of input.permissions)if(!principal.permissions.has(permission))throw new ServiceError(403,"FORBIDDEN","Token 权限不能超过当前用户");const requested=input.nodeScope; if(principal.nodeScope!=="all"&&(requested==="all"||requested.some(id=>!principal.nodeScope.includes(id))))throw new ServiceError(403,"FORBIDDEN","Token 节点范围不能超过当前用户");const id=randomUUID(),token=`sp_${randomToken(32)}`,createdAt=new Date().toISOString();this.database.transaction(()=>{this.database.prepare("INSERT INTO api_tokens(id,user_id,name,token_digest,all_nodes,created_at,expires_at) VALUES(?,?,?,?,?,?,?)").run(id,principal.userId,input.name,digest(token),requested==="all"?1:0,createdAt,input.expiresAt);for(const p of input.permissions)this.database.prepare("INSERT INTO api_token_permissions(token_id,permission_key) VALUES(?,?)").run(id,p);if(requested!=="all")for(const nodeId of requested)this.database.prepare("INSERT INTO api_token_node_scopes(token_id,node_id) VALUES(?,?)").run(id,nodeId);})();return{token,record:{id,name:input.name,permissions:input.permissions,nodeScope:requested,createdAt,expiresAt:input.expiresAt,lastUsedAt:null,revokedAt:null}};}
  listApiTokens(userId:string):ApiTokenRecord[]{const rows=this.database.prepare("SELECT * FROM api_tokens WHERE user_id=? ORDER BY created_at DESC").all(userId) as Array<Record<string,unknown>>;return rows.map(row=>({id:row.id as string,name:row.name as string,permissions:(this.database.prepare("SELECT permission_key AS key FROM api_token_permissions WHERE token_id=?").all(row.id) as Array<{key:Permission}>).map(x=>x.key),nodeScope:row.all_nodes?"all":(this.database.prepare("SELECT node_id AS id FROM api_token_node_scopes WHERE token_id=?").all(row.id) as Array<{id:string}>).map(x=>x.id),createdAt:row.created_at as string,expiresAt:row.expires_at as string|null,lastUsedAt:row.last_used_at as string|null,revokedAt:row.revoked_at as string|null}));}
  revokeToken(userId:string,id:string){const result=this.database.prepare("UPDATE api_tokens SET revoked_at=? WHERE id=? AND user_id=? AND revoked_at IS NULL").run(new Date().toISOString(),id,userId);if(!result.changes)throw new ServiceError(404,"NOT_FOUND","Token 不存在");}
  listRoles(){return (this.database.prepare("SELECT id,name,description,builtin FROM roles ORDER BY builtin DESC,name").all() as Array<{id:string;name:string;description:string;builtin:number}>).map((row)=>({...row,builtin:Boolean(row.builtin),permissions:(this.database.prepare("SELECT permission_key FROM role_permissions WHERE role_id=?").all(row.id) as Array<{permission_key:Permission}>).map(x=>x.permission_key)}));}
  listUsers(){return (this.database.prepare("SELECT * FROM users ORDER BY username").all() as UserRow[]).map(row=>{const user=this.publicUser(row);return{id:user.id,username:user.username,displayName:user.displayName,disabled:Boolean(row.disabled_at),roles:user.roles,nodeScope:user.nodeScope};});}
  private currentSessionPrincipal(principal:Principal){if(principal.type!=="session")throw new ServiceError(403,"FORBIDDEN","身份授权操作需要用户会话");const session=this.database.prepare("SELECT user_id,csrf_digest FROM sessions WHERE id_digest=? AND user_id=? AND revoked_at IS NULL AND expires_at>?").get(principal.id,principal.userId,new Date().toISOString()) as {user_id:string;csrf_digest:string}|undefined;const user=session?this.userById(session.user_id):undefined;if(!session||!user||user.disabled_at)throw new ServiceError(403,"FORBIDDEN","当前会话已失效");return this.principalForUser(user,"session",principal.id,session.csrf_digest);}
  private assertGrantWithinPrincipal(principal:Principal,roleIds:string[],nodeScope:NodeScope){const current=this.currentSessionPrincipal(principal);if(roleIds.includes("administrator")&&(!current.user.roles.includes("administrator")||current.nodeScope!=="all"))throw new ServiceError(403,"FORBIDDEN","只有全节点管理员可以授予管理员角色");const requested=this.database.prepare(`SELECT DISTINCT permission_key AS key FROM role_permissions WHERE role_id IN (${roleIds.map(()=>"?").join(",")})`).all(...roleIds) as Array<{key:Permission}>;for(const {key} of requested)if(!current.permissions.has(key))throw new ServiceError(403,"FORBIDDEN","用户角色不能超过当前用户权限");if(current.nodeScope!=="all"&&(nodeScope==="all"||nodeScope.some(id=>!current.nodeScope.includes(id))))throw new ServiceError(403,"FORBIDDEN","用户节点范围不能超过当前用户");}
  async createUser(principal:Principal,username:string,displayName:string,password:string,roleIds:string[],nodeScope:NodeScope){this.validatePassword(password);this.assertGrantWithinPrincipal(principal,roleIds,nodeScope);const id=randomUUID(),now=new Date().toISOString(),passwordHash=await hash(password,argon);this.database.transaction(()=>{this.assertGrantWithinPrincipal(principal,roleIds,nodeScope);this.database.prepare("INSERT INTO users(id,username,password_hash,display_name,password_changed_at,created_at,updated_at)VALUES(?,?,?,?,?,?,?)").run(id,username,passwordHash,displayName,now,now,now);for(const role of roleIds)this.database.prepare("INSERT INTO user_roles(user_id,role_id)VALUES(?,?)").run(id,role);if(nodeScope!=="all")for(const node of nodeScope)this.database.prepare("INSERT INTO user_node_scopes(user_id,node_id)VALUES(?,?)").run(id,node);})();return id;}
  updateUserAccess(principal:Principal,userId:string,roleIds:string[],nodeScope:NodeScope,disabled:boolean){const isAdmin=Boolean(this.database.prepare("SELECT 1 FROM user_roles WHERE user_id=? AND role_id='administrator'").get(userId));if(isAdmin&&(!roleIds.includes("administrator")||disabled)){const count=(this.database.prepare("SELECT count(DISTINCT ur.user_id) AS count FROM user_roles ur JOIN users u ON u.id=ur.user_id WHERE ur.role_id='administrator' AND u.disabled_at IS NULL").get() as {count:number}).count;if(count<=1)throw new ServiceError(409,"BAD_REQUEST","不能移除或禁用最后一位管理员");}this.database.transaction(()=>{this.assertGrantWithinPrincipal(principal,roleIds,nodeScope);const result=this.database.prepare("UPDATE users SET disabled_at=?,updated_at=?,version=version+1 WHERE id=?").run(disabled?new Date().toISOString():null,new Date().toISOString(),userId);if(!result.changes)throw new ServiceError(404,"NOT_FOUND","用户不存在");this.database.prepare("DELETE FROM user_roles WHERE user_id=?").run(userId);this.database.prepare("DELETE FROM user_node_scopes WHERE user_id=?").run(userId);for(const role of roleIds)this.database.prepare("INSERT INTO user_roles(user_id,role_id)VALUES(?,?)").run(userId,role);if(nodeScope!=="all")for(const node of nodeScope)this.database.prepare("INSERT INTO user_node_scopes(user_id,node_id)VALUES(?,?)").run(userId,node);if(disabled)this.logoutAll(userId);})();}
  upsertRole(principal:Principal,id:string,name:string,description:string,permissions:Permission[]){if(["administrator","operator","audit-reader"].includes(id))throw new ServiceError(403,"FORBIDDEN","内置角色不可修改");for(const permission of permissions)if(!principal.permissions.has(permission))throw new ServiceError(403,"FORBIDDEN","角色权限不能超过当前用户");this.database.transaction(()=>{this.database.prepare("INSERT INTO roles(id,name,description,builtin,created_at)VALUES(?,?,?,0,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description").run(id,name,description,new Date().toISOString());this.database.prepare("DELETE FROM role_permissions WHERE role_id=?").run(id);for(const permission of permissions)this.database.prepare("INSERT INTO role_permissions(role_id,permission_key)VALUES(?,?)").run(id,permission);})();}
}
