import assert from "node:assert/strict";
import { once } from "node:events";
import { access, mkdir, mkdtemp, readFile, realpath, rename, rm, stat, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { FileService } from "../../apps/controller/dist/modules/files/fileService.js";
import { createStackPilotServer } from "../../apps/controller/dist/server.js";
import { createControllerServices } from "../../apps/controller/dist/app.js";
import { loadControllerConfig } from "../../apps/controller/dist/config/environment.js";
import { openDatabase } from "../../apps/controller/dist/database/database.js";
import { IdentityService } from "../../apps/controller/dist/identity/identityService.js";
import { SqliteFileTrashRepository } from "../../apps/controller/dist/modules/files/fileTrashRepository.js";
import { FileTrashService } from "../../apps/controller/dist/modules/files/fileTrashService.js";
import { FakePlatformAdapter } from "./support/fakePlatform.js";

async function fixture(callback){const root=await mkdtemp(join(tmpdir(),"stackpilot-files-"));try{await callback(root);}finally{await rm(root,{recursive:true,force:true});}}

test("file service persists the real lifecycle under an allowed root",async()=>fixture(async(root)=>{const service=new FileService([root]),previousUmask=process.umask(0o077);try{assert.equal((await service.list(root)).parentPath,null);await service.createDirectory(root,"site");assert.equal((await stat(join(root,"site"))).mode&0o777,0o775);const file=await service.upload(join(root,"site"),"index.html",Buffer.from("release"));assert.equal((await stat(file.path)).mode&0o777,0o664);assert.equal((await readFile(file.path,"utf8")),"release");const renamed=await service.rename(file.path,"app.html");assert.equal(renamed.name,"app.html");assert.equal((await service.list(join(root,"site"))).entries[0].name,"app.html");await service.moveToTrash(renamed.path);assert.deepEqual((await service.list(join(root,"site"))).entries,[]);}finally{process.umask(previousUmask);}}));

test("file service and trash service restore and purge real filesystem entries",async()=>fixture(async(root)=>{const database=openDatabase(":memory:"),repository=new SqliteFileTrashRepository(database),files=new FileService([root],repository),trash=new FileTrashService(repository,files);try{await writeFile(join(root,"restore.txt"),"restore");await files.moveToTrash(join(root,"restore.txt"),"admin");const restored=trash.list().entries[0];assert.equal(await access(restored.originalPath).then(()=>true,()=>false),false);await trash.restore(restored.id,"admin");assert.equal(await readFile(restored.originalPath,"utf8"),"restore");await writeFile(join(root,"purge.txt"),"purge");await files.moveToTrash(join(root,"purge.txt"),"admin");const purged=trash.list().entries[0];const storage=repository.storagePath(purged.id);assert(storage);await trash.purge(purged.id);assert.equal(await access(storage).then(()=>true,()=>false),false);assert.equal(trash.list().entries.length,0);}finally{database.close();}}));

test("trash filesystem operations reject forged storage paths",async()=>fixture(async(root)=>{const outside=await mkdtemp(join(tmpdir(),"stackpilot-trash-outside-"));try{const service=new FileService([root]);await writeFile(join(outside,"secret.txt"),"secret");await assert.rejects(service.restoreFromTrash(join(root,"restored.txt"),join(outside,"secret.txt")),/回收站存储路径无效/);await assert.rejects(service.stageTrashPurge(join(root,".stackpilot-trash","not-a-uuid","secret.txt")),/回收站存储路径无效/);assert.equal(await readFile(join(outside,"secret.txt"),"utf8"),"secret");}finally{await rm(outside,{recursive:true,force:true});}}));

test("purge retry reconciles a missing trash bucket with its active database row",async()=>fixture(async(root)=>{const database=openDatabase(":memory:"),repository=new SqliteFileTrashRepository(database),files=new FileService([root],repository),trash=new FileTrashService(repository,files);try{await writeFile(join(root,"retry.txt"),"retry");await files.moveToTrash(join(root,"retry.txt"),"admin");const entry=trash.list().entries[0],storage=repository.storagePath(entry.id);assert(storage);await rm(join(root,".stackpilot-trash"),{recursive:true,force:true});await trash.purge(entry.id);assert.equal(trash.list().entries.length,0);}finally{database.close();}}));

test("purge rolls the bucket back when the database transition fails",async()=>fixture(async(root)=>{const database=openDatabase(":memory:"),repository=new SqliteFileTrashRepository(database),files=new FileService([root],repository);try{await writeFile(join(root,"purge-rollback.txt"),"rollback");await files.moveToTrash(join(root,"purge-rollback.txt"),"admin");const entry=repository.listActive()[0],storage=repository.storagePath(entry.id);assert(storage);const failingRepository={...repository,listActive:()=>repository.listActive(),listRecentlyRestored:(limit)=>repository.listRecentlyRestored(limit),storagePath:(id)=>repository.storagePath(id),restore:(id,at,actor)=>repository.restore(id,at,actor),purge:()=>{throw new Error("database unavailable");},purgeAll:(at)=>repository.purgeAll(at),create:(value,path)=>repository.create(value,path)};const trash=new FileTrashService(failingRepository,files);await assert.rejects(trash.purge(entry.id),/database unavailable/);assert.equal(await readFile(storage,"utf8"),"rollback");assert.equal(repository.listActive().length,1);}finally{database.close();}}));

test("purge all rolls every staged bucket back when the database transaction fails",async()=>fixture(async(root)=>{const database=openDatabase(":memory:"),repository=new SqliteFileTrashRepository(database),files=new FileService([root],repository);try{for(const name of ["first.txt","second.txt"]){await writeFile(join(root,name),name);await files.moveToTrash(join(root,name),"admin");}const entries=repository.listActive(),storage=entries.map((entry)=>repository.storagePath(entry.id));assert(storage.every(Boolean));const failingRepository={...repository,listActive:()=>repository.listActive(),listRecentlyRestored:(limit)=>repository.listRecentlyRestored(limit),storagePath:(id)=>repository.storagePath(id),restore:(id,at,actor)=>repository.restore(id,at,actor),purge:(id,at)=>repository.purge(id,at),purgeAll:()=>{throw new Error("database unavailable");},create:(value,path)=>repository.create(value,path)};const trash=new FileTrashService(failingRepository,files);await assert.rejects(trash.purgeAll(),/database unavailable/);assert.equal(repository.listActive().length,2);for(const path of storage)assert.equal(await access(path).then(()=>true,()=>false),true);}finally{database.close();}}));

test("restore rolls the file back when the database transition fails",async()=>fixture(async(root)=>{const database=openDatabase(":memory:"),repository=new SqliteFileTrashRepository(database),files=new FileService([root],repository);try{await writeFile(join(root,"rollback.txt"),"rollback");await files.moveToTrash(join(root,"rollback.txt"),"admin");const entry=repository.listActive()[0],storage=repository.storagePath(entry.id);assert(storage);const failingRepository={...repository,listActive:()=>repository.listActive(),listRecentlyRestored:(limit)=>repository.listRecentlyRestored(limit),storagePath:(id)=>repository.storagePath(id),restore:()=>{throw new Error("database unavailable");},purge:(id,at)=>repository.purge(id,at),purgeAll:(at)=>repository.purgeAll(at),create:(value,path)=>repository.create(value,path)};const trash=new FileTrashService(failingRepository,files);await assert.rejects(trash.restore(entry.id,"admin"),/database unavailable/);assert.equal(await access(entry.originalPath).then(()=>true,()=>false),false);assert.equal(await readFile(storage,"utf8"),"rollback");assert.equal(repository.listActive().length,1);}finally{database.close();}}));

test("file service rejects traversal, symlink escape and protected trash paths",async()=>fixture(async(root)=>{const outside=await mkdtemp(join(tmpdir(),"stackpilot-outside-"));try{await writeFile(join(outside,"secret"),"secret");await symlink(outside,join(root,"escape"));const service=new FileService([root]);await assert.rejects(service.list(join(root,"..")),/允许范围/);await assert.rejects(service.list(join(root,"escape")),/符号链接/);await assert.rejects(service.createDirectory(root,".stackpilot-trash"),/文件名无效/);await writeFile(join(root,"trash-me.txt"),"trash");await service.moveToTrash(join(root,"trash-me.txt"));await assert.rejects(service.list(join(root,".stackpilot-trash")),/不可直接访问/);}finally{await rm(outside,{recursive:true,force:true});}}));

test("file mutations reject a validated parent moved outside the allowed root",{skip:process.platform!=="linux"},async()=>fixture(async(root)=>{const outside=await mkdtemp(join(tmpdir(),"stackpilot-outside-")),site=join(root,"site"),moved=join(outside,"site-moved");try{await mkdir(site);const service=new FileService([root]),stable=service.withStableDirectory.bind(service);let replaced=false;service.withStableDirectory=(value,operation)=>stable(value,async(directory)=>{if(!replaced&&value===site){replaced=true;await rename(site,moved);await symlink(outside,site);}return operation(directory);});await assert.rejects(service.upload(site,"index.html",Buffer.from("blocked")),/目录在操作前发生变化/);await assert.rejects(access(join(moved,"index.html")));}finally{await rm(outside,{recursive:true,force:true});}}));

test("concurrent renames never overwrite the winning target",async()=>fixture(async(root)=>{await writeFile(join(root,"first.txt"),"first");await writeFile(join(root,"second.txt"),"second");const service=new FileService([root]),results=await Promise.allSettled([service.rename(join(root,"first.txt"),"target.txt"),service.rename(join(root,"second.txt"),"target.txt")]);assert.equal(results.filter((result)=>result.status==="fulfilled").length,1);assert.equal(results.filter((result)=>result.status==="rejected").length,1);const target=await readFile(join(root,"target.txt"),"utf8"),remaining=target==="first"?"second.txt":"first.txt";assert.equal(await readFile(join(root,remaining),"utf8"),target==="first"?"second":"first");}));

test("independent file services atomically refuse rename overwrite",async()=>fixture(async(root)=>{await writeFile(join(root,"first.txt"),"first");await writeFile(join(root,"second.txt"),"second");const results=await Promise.allSettled([new FileService([root]).rename(join(root,"first.txt"),"target.txt"),new FileService([root]).rename(join(root,"second.txt"),"target.txt")]);assert.equal(results.filter((result)=>result.status==="fulfilled").length,1);assert.equal(results.filter((result)=>result.status==="rejected").length,1);const target=await readFile(join(root,"target.txt"),"utf8"),remaining=target==="first"?"second.txt":"first.txt";assert.equal(await readFile(join(root,remaining),"utf8"),target==="first"?"second":"first");}));

test("directory rename is rejected without atomic no-replace support",async()=>fixture(async(root)=>{await mkdir(join(root,"site"));await assert.rejects(new FileService([root]).rename(join(root,"site"),"renamed"),/仅支持重命名普通文件/);assert.equal((await stat(join(root,"site"))).isDirectory(),true);}));

test("file HTTP API enforces permissions before accepting raw uploads",async()=>fixture(async(root)=>{const database=openDatabase(":memory:"),identity=new IdentityService(database,Buffer.alloc(32,9));await identity.createInitialAdministrator("admin","Administrator","correct horse battery staple");const admin=(await identity.login("admin","correct horse battery staple","files-test","node-test")).principal;const readToken=identity.createApiToken(admin,{name:"files-read",permissions:["files:read"],nodeScope:"all",expiresAt:null}).token,manageToken=identity.createApiToken(admin,{name:"files-manage",permissions:["files:read","files:manage"],nodeScope:"all",expiresAt:null}).token;const config=loadControllerConfig({STACKPILOT_COOKIE_SECURE:"0",STACKPILOT_FILE_ROOTS:root}),platform=new FakePlatformAdapter(),services=createControllerServices(platform,process.cwd(),config);const server=createStackPilotServer({config,platform,services,database,identity});server.listen(0,"127.0.0.1");await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,auth=(token,extra={})=>({Authorization:`Bearer ${token}`,...extra});try{assert.equal((await fetch(`${base}/api/files?path=${encodeURIComponent(root)}`)).status,401);const defaultRoot=await (await fetch(`${base}/api/files`,{headers:auth(readToken)})).json();assert.equal(defaultRoot.rootPath,root);assert.equal(defaultRoot.path,await realpath(root));assert.equal((await fetch(`${base}/api/files?path=${encodeURIComponent(root)}`,{headers:auth(readToken)})).status,200);assert.equal((await fetch(`${base}/api/files/directories`,{method:"POST",headers:auth(readToken,{"Content-Type":"application/json"}),body:JSON.stringify({path:root,name:"denied"})})).status,403);assert.equal((await fetch(`${base}/api/files/upload`,{method:"POST",headers:auth(readToken,{"Content-Type":"application/octet-stream","X-File-Path":root,"X-File-Name":"denied.txt"}),body:"denied"})).status,403);const upload=await fetch(`${base}/api/files/upload`,{method:"POST",headers:auth(manageToken,{"Content-Type":"application/octet-stream","X-File-Path":root,"X-File-Name":"hello.txt"}),body:"hello"});assert.equal(upload.status,201);assert.equal(await readFile(join(root,"hello.txt"),"utf8"),"hello");}finally{server.close();await once(server,"close");database.close();}}));
