import assert from "node:assert/strict";
import { once } from "node:events";
import { mkdtemp, readFile, rm, stat, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { FileService } from "../../apps/controller/dist/modules/files/fileService.js";
import { createStackPilotServer } from "../../apps/controller/dist/server.js";
import { createControllerServices } from "../../apps/controller/dist/app.js";
import { loadControllerConfig } from "../../apps/controller/dist/config/environment.js";
import { openDatabase } from "../../apps/controller/dist/database/database.js";
import { IdentityService } from "../../apps/controller/dist/identity/identityService.js";
import { FakePlatformAdapter } from "./support/fakePlatform.js";

async function fixture(callback){const root=await mkdtemp(join(tmpdir(),"stackpilot-files-"));try{await callback(root);}finally{await rm(root,{recursive:true,force:true});}}

test("file service persists the real lifecycle under an allowed root",async()=>fixture(async(root)=>{const service=new FileService([root]),previousUmask=process.umask(0o077);try{assert.equal((await service.list(root)).parentPath,null);await service.createDirectory(root,"site");assert.equal((await stat(join(root,"site"))).mode&0o777,0o775);const file=await service.upload(join(root,"site"),"index.html",Buffer.from("release"));assert.equal((await stat(file.path)).mode&0o777,0o664);assert.equal((await readFile(file.path,"utf8")),"release");const renamed=await service.rename(file.path,"app.html");assert.equal(renamed.name,"app.html");assert.equal((await service.list(join(root,"site"))).entries[0].name,"app.html");await service.moveToTrash(renamed.path);assert.deepEqual((await service.list(join(root,"site"))).entries,[]);}finally{process.umask(previousUmask);}}));

test("file service rejects traversal, symlink escape and protected trash names",async()=>fixture(async(root)=>{const outside=await mkdtemp(join(tmpdir(),"stackpilot-outside-"));try{await writeFile(join(outside,"secret"),"secret");await symlink(outside,join(root,"escape"));const service=new FileService([root]);await assert.rejects(service.list(join(root,"..")),/允许范围/);await assert.rejects(service.list(join(root,"escape")),/符号链接/);await assert.rejects(service.createDirectory(root,".stackpilot-trash"),/文件名无效/);}finally{await rm(outside,{recursive:true,force:true});}}));

test("concurrent renames never overwrite the winning target",async()=>fixture(async(root)=>{await writeFile(join(root,"first.txt"),"first");await writeFile(join(root,"second.txt"),"second");const service=new FileService([root]),results=await Promise.allSettled([service.rename(join(root,"first.txt"),"target.txt"),service.rename(join(root,"second.txt"),"target.txt")]);assert.equal(results.filter((result)=>result.status==="fulfilled").length,1);assert.equal(results.filter((result)=>result.status==="rejected").length,1);const target=await readFile(join(root,"target.txt"),"utf8"),remaining=target==="first"?"second.txt":"first.txt";assert.equal(await readFile(join(root,remaining),"utf8"),target==="first"?"second":"first");}));

test("file HTTP API enforces permissions before accepting raw uploads",async()=>fixture(async(root)=>{const database=openDatabase(":memory:"),identity=new IdentityService(database,Buffer.alloc(32,9));await identity.createInitialAdministrator("admin","Administrator","correct horse battery staple");const admin=(await identity.login("admin","correct horse battery staple","files-test","node-test")).principal;const readToken=identity.createApiToken(admin,{name:"files-read",permissions:["files:read"],nodeScope:"all",expiresAt:null}).token,manageToken=identity.createApiToken(admin,{name:"files-manage",permissions:["files:read","files:manage"],nodeScope:"all",expiresAt:null}).token;const config=loadControllerConfig({STACKPILOT_COOKIE_SECURE:"0",STACKPILOT_FILE_ROOTS:root}),platform=new FakePlatformAdapter(),services=createControllerServices(platform,process.cwd(),config);const server=createStackPilotServer({config,platform,services,database,identity});server.listen(0,"127.0.0.1");await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,auth=(token,extra={})=>({Authorization:`Bearer ${token}`,...extra});try{assert.equal((await fetch(`${base}/api/files?path=${encodeURIComponent(root)}`)).status,401);assert.equal((await fetch(`${base}/api/files?path=${encodeURIComponent(root)}`,{headers:auth(readToken)})).status,200);assert.equal((await fetch(`${base}/api/files/directories`,{method:"POST",headers:auth(readToken,{"Content-Type":"application/json"}),body:JSON.stringify({path:root,name:"denied"})})).status,403);assert.equal((await fetch(`${base}/api/files/upload`,{method:"POST",headers:auth(readToken,{"Content-Type":"application/octet-stream","X-File-Path":root,"X-File-Name":"denied.txt"}),body:"denied"})).status,403);const upload=await fetch(`${base}/api/files/upload`,{method:"POST",headers:auth(manageToken,{"Content-Type":"application/octet-stream","X-File-Path":root,"X-File-Name":"hello.txt"}),body:"hello"});assert.equal(upload.status,201);assert.equal(await readFile(join(root,"hello.txt"),"utf8"),"hello");}finally{server.close();await once(server,"close");database.close();}}));
