import assert from "node:assert/strict";
import { once } from "node:events";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { openDatabase } from "../../apps/controller/dist/database/database.js";
import { migrateDatabase } from "../../apps/controller/dist/database/migrator.js";
import { IdentityService } from "../../apps/controller/dist/identity/identityService.js";
import { SecretStore } from "../../apps/controller/dist/security/secretStore.js";
import { SqliteAgentControlRepository } from "../../apps/controller/dist/repositories/sqliteAgentControlRepository.js";
import { createStackPilotServer } from "../../apps/controller/dist/server.js";
import { FakePlatformAdapter } from "./support/fakePlatform.js";

const password="correct horse battery staple";const origin="http://127.0.0.1:5173";
async function fixture(callback,sessionSeconds=3600){const database=openDatabase(":memory:");const identity=new IdentityService(database,Buffer.alloc(32,9),sessionSeconds);await identity.createInitialAdministrator("admin","Administrator",password);try{await callback({database,identity});}finally{database.close();}}
async function serve(callback,sessionSeconds=3600){await fixture(async({database,identity})=>{const server=createStackPilotServer({env:{STACKPILOT_COOKIE_SECURE:"0",STACKPILOT_ALLOWED_ORIGINS:origin},database,identity,platform:new FakePlatformAdapter()});server.listen(0,"127.0.0.1");await once(server,"listening");try{await callback(`http://127.0.0.1:${server.address().port}`,identity);}finally{server.close();await once(server,"close");}},sessionSeconds);}
function cookie(response){return response.headers.get("set-cookie")?.split(";")[0]??"";}

test("initial administrator is one-time and login does not enumerate users",async()=>fixture(async({identity})=>{await assert.rejects(identity.createInitialAdministrator("second","Second Administrator",password),/初始化/);for(const username of ["admin","missing"]){await assert.rejects(identity.login(username,"wrong password value","source","agent"),error=>error.message==="用户名或密码无效");}}));
test("cookie login rotates sessions, enforces CSRF and supports logout",async()=>serve(async(base)=>{const login=await fetch(`${base}/api/auth/login`,{method:"POST",headers:{Origin:origin,"Content-Type":"application/json"},body:JSON.stringify({username:"admin",password})});assert.equal(login.status,200);const body=await login.json();const session=cookie(login);assert.match(login.headers.get("set-cookie"),/HttpOnly.*SameSite=Strict/);const missing=await fetch(`${base}/api/auth/logout`,{method:"POST",headers:{Cookie:session,Origin:origin,"Content-Type":"application/json"},body:"{}"});assert.equal(missing.status,403);const wrongOrigin=await fetch(`${base}/api/auth/logout`,{method:"POST",headers:{Cookie:session,Origin:"https://attacker.example","X-CSRF-Token":body.csrfToken,"Content-Type":"application/json"},body:"{}"});assert.equal(wrongOrigin.status,403);const logout=await fetch(`${base}/api/auth/logout`,{method:"POST",headers:{Cookie:session,Origin:origin,"X-CSRF-Token":body.csrfToken,"Content-Type":"application/json"},body:"{}"});assert.equal(logout.status,200);assert.equal((await fetch(`${base}/api/auth/me`,{headers:{Cookie:session}})).status,401);}));
test("expired session and login failure backoff fail closed",async()=>fixture(async({identity,database})=>{const login=await identity.login("admin",password,"src","ua");database.prepare("UPDATE sessions SET expires_at=?").run(new Date(0).toISOString());assert.equal(identity.authenticateSession(login.sessionToken),null);for(let i=0;i<3;i++)await assert.rejects(identity.login("admin","invalid password","brute","ua"));await assert.rejects(identity.login("admin","invalid password","brute","ua"),error=>error.status===429);}));
test("explicit permissions, node scopes and token revocation are enforced",async()=>fixture(async({identity,database})=>{const admin=await identity.login("admin",password,"src2","ua");await identity.createUser(admin.principal,"reader","Reader User",password,["audit-reader"],["11111111-1111-4111-8111-111111111111"]);const login=await identity.login("reader",password,"src","ua");identity.require(login.principal,"nodes:read","11111111-1111-4111-8111-111111111111");assert.throws(()=>identity.require(login.principal,"tasks:create"),/权限不足/);assert.throws(()=>identity.require(login.principal,"nodes:read","22222222-2222-4222-8222-222222222222"),/节点/);const created=identity.createApiToken(admin.principal,{name:"scoped",permissions:["nodes:read"],nodeScope:["11111111-1111-4111-8111-111111111111"],expiresAt:null});const principal=identity.authenticateApiToken(created.token);assert(principal);identity.require(principal,"nodes:read","11111111-1111-4111-8111-111111111111");assert.throws(()=>identity.require(principal,"overview:read"));identity.revokeToken(admin.principal.userId,created.record.id);assert.equal(identity.authenticateApiToken(created.token),null);assert.doesNotMatch(JSON.stringify(database.prepare("SELECT * FROM api_tokens").all()),new RegExp(created.token));}));
test("built-in roles preserve database and scoped file access",async()=>fixture(async({identity})=>{const roles=new Map(identity.listRoles().map(role=>[role.id,new Set(role.permissions)]));assert.equal(roles.get("administrator")?.has("files:delete"),true);assert.equal(roles.get("operator")?.has("databases:read"),true);assert.equal(roles.get("operator")?.has("files:write"),true);assert.equal(roles.get("audit-reader")?.has("databases:read"),true);}));
test("delegated identity managers cannot grant authority they do not hold",async()=>fixture(async({identity})=>{const admin=(await identity.login("admin",password,"admin-src","ua")).principal;identity.upsertRole(admin,"role-manager","Role Manager","",["roles:manage"]);identity.upsertRole(admin,"user-manager","User Manager","",["users:manage"]);identity.upsertRole(admin,"high-role","High Role","",["users:manage","audit:read"]);await identity.createUser(admin,"role-manager","Role Manager",password,["role-manager"],[]);await identity.createUser(admin,"user-manager","User Manager",password,["user-manager"],[]);const roleManager=(await identity.login("role-manager",password,"role-src","ua")).principal;assert.throws(()=>identity.upsertRole(roleManager,"role-manager","Role Manager","",["roles:manage","audit:read"]),/角色权限不能超过/);identity.upsertRole(roleManager,"limited-role","Limited Role","",["roles:manage"]);const userManager=(await identity.login("user-manager",password,"user-src","ua")).principal;await assert.rejects(identity.createUser(userManager,"elevated","Elevated User",password,["administrator"],[]),/全节点管理员/);await assert.rejects(identity.createUser(userManager,"custom-elevated","Custom Elevated",password,["high-role"],[]),/用户角色不能超过/);await assert.rejects(identity.createUser(userManager,"wide-scope","Wide Scope",password,["user-manager"],"all"),/节点范围不能超过/);const limitedId=await identity.createUser(userManager,"limited","Limited User",password,["user-manager"],[]);assert.throws(()=>identity.updateUserAccess(userManager,limitedId,["administrator"],[],false),/全节点管理员/);identity.updateUserAccess(userManager,limitedId,["user-manager"],[],false);const limited=(await identity.login("limited",password,"limited-src","ua")).principal;assert.deepEqual([...limited.permissions],["users:manage"]);assert.deepEqual(limited.nodeScope,[]);const scopedAdminToken=identity.createApiToken(admin,{name:"scoped-admin",permissions:[...admin.permissions],nodeScope:[],expiresAt:null});const scopedAdmin=identity.authenticateApiToken(scopedAdminToken.token);assert(scopedAdmin);await assert.rejects(identity.createUser(scopedAdmin,"token-admin","Token Admin",password,["administrator"],[]),/用户会话/);const secondAdmin=await identity.createUser(admin,"second-admin","Second Admin",password,["administrator"],"all");assert.equal(identity.listUsers().find(user=>user.id===secondAdmin)?.nodeScope,"all");}));
test("user creation rechecks the caller after password hashing",async()=>fixture(async({identity})=>{const admin=(await identity.login("admin",password,"race-admin","ua")).principal;identity.upsertRole(admin,"user-manager","User Manager","",["users:manage"]);await identity.createUser(admin,"manager","Manager",password,["user-manager"],[]);const manager=(await identity.login("manager",password,"race-manager","ua")).principal;const pending=identity.createUser(manager,"raced-user","Raced User",password,["user-manager"],[]);identity.updateUserAccess(admin,manager.userId,["audit-reader"],[],false);await assert.rejects(pending,/用户角色不能超过/);assert.equal(identity.listUsers().some(user=>user.username==="raced-user"),false);}));
test("secrets use authenticated encryption and audit chain detects tampering",async()=>fixture(async({identity,database})=>{const store=new SecretStore(database,Buffer.alloc(32,1));store.set("node-secret",Buffer.from("credential-value"));assert.equal(store.get("node-secret")?.toString(),"credential-value");assert.doesNotMatch(JSON.stringify(database.prepare("SELECT hex(ciphertext) AS value FROM encrypted_secrets").all()),/credential-value/);identity.audit.append({actorType:"user",actorId:"admin",source:"test",action:"test.one",outcome:"success",authorization:"allowed",requestId:crypto.randomUUID()});identity.audit.append({actorType:"user",actorId:"admin",source:"test",action:"test.two",outcome:"success",authorization:"allowed",requestId:crypto.randomUUID()});assert.deepEqual(identity.audit.verify(),{valid:true,count:2});database.exec("DROP TRIGGER audit_events_no_update");database.prepare("UPDATE audit_events SET outcome='changed' WHERE sequence=1").run();assert.equal(identity.audit.verify().valid,false);}));
test("migration failure rolls back and concurrent repository updates are serialized",async()=>fixture(async({database})=>{assert.throws(()=>migrateDatabase(database,[{version:4,name:"broken",sql:"CREATE TABLE rollback_probe(id TEXT); INSERT INTO missing_table VALUES(1)"}]));assert.equal(database.prepare("SELECT name FROM sqlite_master WHERE name='rollback_probe'").get(),undefined);assert.equal(database.prepare("SELECT max(version) AS version FROM schema_migrations").get().version,3);const repository=new SqliteAgentControlRepository(database);await Promise.all(Array.from({length:20},(_,index)=>repository.update(state=>state.nonces.push({credentialId:`credential-${index}`,nonce:`nonce-${index}`,expiresAt:new Date(Date.now()+60_000).toISOString()}))));assert.equal((await repository.read()).nonces.length,20);}));
test("SQLite online backup restores data and passes integrity check",async()=>{const directory=await mkdtemp(join(tmpdir(),"stackpilot-db-"));const source=join(directory,"source.db"),backup=join(directory,"backup.db");try{const database=openDatabase(source);const identity=new IdentityService(database,Buffer.alloc(32,3));await identity.createInitialAdministrator("admin","Admin",password);await database.backup(backup);database.close();const restored=openDatabase(backup);assert.equal(restored.pragma("integrity_check",{simple:true}),"ok");assert.equal(restored.prepare("SELECT count(*) AS count FROM users").get().count,1);restored.close();assert((await readFile(backup)).length>0);}finally{await rm(directory,{recursive:true,force:true});}});
