import { Clock3, FileBox, RefreshCw, Trash2 } from "lucide-react";
import { useRef, useState } from "react";
import { resolvePageMeta } from "../../app/navigation";
import { ModulePageShell } from "../../components/layout/ModulePageShell";
import { MetricTile, ModuleSearch } from "../../components/ui/Cards";
import { ConfirmDialog } from "../../components/ui/ConfirmDialog";
import { DataTable } from "../../components/ui/DataTable";
import { DetailDrawer } from "../../components/ui/DetailDrawer";
import { FieldSelect } from "../../components/ui/FormControls";
import type { Notify, PageKey } from "../../types/app";
import { currentClock } from "../../utils/time";
import type { FileRecord, TrashFileRecord } from "./types";

export function FileTrashPage({page,notify,trashRows,setTrashRows,restoredRows,setRestoredRows,setFiles}:{page:PageKey;notify:Notify;trashRows:TrashFileRecord[];setTrashRows:React.Dispatch<React.SetStateAction<TrashFileRecord[]>>;restoredRows:FileRecord[];setRestoredRows:React.Dispatch<React.SetStateAction<FileRecord[]>>;setFiles:React.Dispatch<React.SetStateAction<FileRecord[]>>}){
  const[search,setSearch]=useState(""),[ownerFilter,setOwnerFilter]=useState("全部"),[selectedId,setSelectedId]=useState("");
  const[confirmation,setConfirmation]=useState<{type:"file";row:TrashFileRecord;returnToDetail:boolean}|{type:"all";count:number}|null>(null),restorePanelRef=useRef<HTMLElement>(null);
  const selected=trashRows.find((row)=>row.id===selectedId)??null,ownerOptions=["全部",...Array.from(new Set(trashRows.map((row)=>row.owner)))];
  const filteredRows=trashRows.filter((row)=>{const query=search.trim().toLowerCase(),match=!query||`${row.name} ${row.originalPath} ${row.reason} ${row.owner}`.toLowerCase().includes(query);return match&&(ownerFilter==="全部"||row.owner===ownerFilter);});
  const restoreFile=(row:TrashFileRecord)=>{const parts=row.originalPath.split("/"),fileName=parts.pop()??row.name,parentPath=parts.join("/")||"/",restored:FileRecord={id:`restore-${Date.now()}`,name:fileName,type:"文件",path:parentPath,size:row.size,modified:currentClock(),owner:row.owner};setRestoredRows((current)=>[restored,...current]);setFiles((current)=>[restored,...current]);setTrashRows((current)=>current.filter((item)=>item.id!==row.id));if(selectedId===row.id)setSelectedId("");notify(`${row.name} 已恢复到 ${parentPath}`);};
  const requestPurge=(row:TrashFileRecord,returnToDetail=false)=>{if(returnToDetail)setSelectedId("");setConfirmation({type:"file",row,returnToDetail});};
  const closeConfirmation=()=>{if(confirmation?.type==="file"&&confirmation.returnToDetail&&trashRows.some((row)=>row.id===confirmation.row.id))setSelectedId(confirmation.row.id);setConfirmation(null);};
  const confirmPurge=()=>{if(!confirmation)return;if(confirmation.type==="all"){setTrashRows([]);setSelectedId("");notify(`已永久删除回收站中的 ${confirmation.count} 个文件`,"danger");setConfirmation(null);return;}const row=confirmation.row;setTrashRows((current)=>current.filter((item)=>item.id!==row.id));if(selectedId===row.id)setSelectedId("");notify(`${row.name} 已永久删除`,"danger");setConfirmation(null);};
  return <>
    <div className="trash-page-layer" inert={Boolean(selected||confirmation)} aria-hidden={selected||confirmation?"true":undefined}>
      <ModulePageShell title={resolvePageMeta(page).title} subtitle="独立回收站视图，支持按所有者筛选、查看删除原因、恢复文件和永久删除。" page={page}
        viewContext={{eyebrow:"文件 / 回收站",title:"回收站",chips:[`待清理 ${trashRows.length}`,`已恢复 ${restoredRows.length}`,"保留 7 天"]}}
        actions={<><button className="ghost" type="button" onClick={()=>{restorePanelRef.current?.scrollIntoView({block:"start"});restorePanelRef.current?.querySelector<HTMLElement>("h2")?.focus({preventScroll:true});}}><RefreshCw size={15}/> 查看恢复记录</button><button className="trash-destructive" type="button" disabled={!trashRows.length} onClick={()=>setConfirmation({type:"all",count:trashRows.length})}><Trash2 size={15}/> 清空回收站</button></>}
        filters={<><ModuleSearch value={search} placeholder="搜索文件、原路径、删除原因" onChange={setSearch}/><FieldSelect label="所有者" value={ownerFilter} options={ownerOptions} onChange={setOwnerFilter}/></>}
        metrics={<><MetricTile icon={Trash2} label="回收站文件" value={`${trashRows.length}`} tone="orange"/><MetricTile icon={RefreshCw} label="已恢复" value={`${restoredRows.length}`} tone="green"/><MetricTile icon={Clock3} label="保留策略" value="7 天" tone="blue"/></>}
        side={selected&&<DetailDrawer title="删除详情" subtitle={selected.name} onClose={()=>setSelectedId("")} className="trash-detail-drawer" modal actions={<><button className="trash-destructive" type="button" aria-label={`永久删除 ${selected.name}`} onClick={()=>requestPurge(selected,true)}>永久删除</button><button className="primary" type="button" aria-label={`恢复 ${selected.name}`} onClick={()=>restoreFile(selected)}>恢复</button></>}><dl className="trash-detail-list"><div><dt>原路径</dt><dd>{selected.originalPath}</dd></div><div><dt>大小</dt><dd>{selected.size}</dd></div><div><dt>删除时间</dt><dd>{selected.deletedAt}</dd></div><div><dt>剩余保留</dt><dd>{selected.expiresIn}</dd></div><div><dt>所有者</dt><dd>{selected.owner}</dd></div><div><dt>删除原因</dt><dd>{selected.reason}</dd></div></dl></DetailDrawer>} sideModal={Boolean(selected)}>
        <div className="file-trash-workspace"><DataTable columns={[
          {key:"name",label:"文件",width:"220px",render:(row)=><button className="module-row-link trash-file-link" type="button" title={row.name} onClick={()=>setSelectedId(row.id)}><Trash2 size={15}/><b>{row.name}</b></button>},{key:"path",label:"原路径",render:(row)=><code className="trash-path" title={row.originalPath}>{row.originalPath}</code>},{key:"size",label:"大小",width:"84px",render:(row)=>row.size},{key:"deleted",label:"删除时间",render:(row)=>row.deletedAt},{key:"expires",label:"剩余保留",width:"92px",render:(row)=><span className="pill orange"><Clock3 size={12}/>{row.expiresIn}</span>},{key:"owner",label:"所有者",width:"84px",render:(row)=>row.owner},{key:"ops",label:"操作",width:"184px",render:(row)=><span className="table-actions"><button type="button" aria-label={`恢复 ${row.name}`} onClick={()=>restoreFile(row)}>恢复</button><button className="trash-destructive small" type="button" aria-label={`永久删除 ${row.name}`} onClick={()=>requestPurge(row)}>永久删除</button></span>},
        ]} rows={filteredRows} emptyText="回收站没有匹配文件" getRowKey={(row)=>row.id} mobileCard={(row)=><><div className="module-card-head trash-mobile-head"><button className="module-row-link trash-file-link" type="button" title={row.name} onClick={()=>setSelectedId(row.id)}><Trash2 size={15}/><b>{row.name}</b></button><span className="pill orange"><Clock3 size={12}/>{row.expiresIn}</span></div><code className="module-card-code">{row.originalPath}</code><div className="module-card-meta"><span><b>大小</b><em>{row.size}</em></span><span><b>删除</b><em>{row.deletedAt}</em></span><span><b>所有者</b><em>{row.owner}</em></span><span className="module-card-span-2"><b>原因</b><em>{row.reason}</em></span></div><div className="module-card-footer"><div className="table-actions actions-2"><button type="button" aria-label={`恢复 ${row.name}`} onClick={()=>restoreFile(row)}>恢复</button><button className="trash-destructive small" type="button" aria-label={`永久删除 ${row.name}`} onClick={()=>requestPurge(row)}>永久删除</button></div></div></>}/>
          <section ref={restorePanelRef} className="trash-restore-panel" aria-labelledby="trash-restore-title"><header className="trash-section-head"><span><RefreshCw size={18}/></span><div><h2 id="trash-restore-title" tabIndex={-1}>最近恢复</h2><p>{restoredRows.length?`${restoredRows.length} 个文件已恢复到原目录`:"恢复后的文件会显示在这里"}</p></div></header><div className="restore-mini-list">{restoredRows.map((row)=><p key={row.id}><span className="restore-file-icon"><FileBox size={16}/></span><span><b>{row.name}</b><em>{row.path}</em></span><time>{row.modified}</time></p>)}{!restoredRows.length&&<div className="trash-empty-state" role="status"><FileBox size={20}/><span>还没有恢复记录</span></div>}</div></section>
        </div>
      </ModulePageShell>
    </div>
    {confirmation&&<ConfirmDialog title={confirmation.type==="all"?"清空回收站":"永久删除文件"} message={confirmation.type==="all"?`将永久删除回收站中的 ${confirmation.count} 个文件，此操作无法撤销。`:`将永久删除 ${confirmation.row.name}，此操作无法撤销。`} detail={confirmation.type==="file"?confirmation.row.originalPath:undefined} confirmLabel={confirmation.type==="all"?"确认清空":"永久删除"} onClose={closeConfirmation} onConfirm={confirmPurge}/>} 
  </>;
}
