import type { Permission } from "@stackpilot/contracts";
import { ChevronRight, CloudUpload, FileBox, Folder, Link2, LoaderCircle, Pencil, Plus, RefreshCw, Trash2 } from "lucide-react";
import { useRef, useState } from "react";
import { createDirectory, deleteFile, renameFile, uploadFile } from "../../api/filesApi";
import { resolvePageMeta } from "../../app/navigation";
import { ModulePageShell } from "../../components/layout/ModulePageShell";
import { ModuleSearch } from "../../components/ui/Cards";
import { DataTable } from "../../components/ui/DataTable";
import { DetailDrawer } from "../../components/ui/DetailDrawer";
import { FieldSelect, FormLine } from "../../components/ui/FormControls";
import type { Notify, PageKey } from "../../types/app";
import { formatBackendDateTime } from "../../utils/time";
import { useFilesData } from "./useFilesData";

type Drawer = { type:"folder" } | { type:"rename"|"delete"; path:string; name:string; kind:"file"|"directory"|"symlink" };
const kindLabel={directory:"文件夹",file:"文件",symlink:"链接"} as const;
function size(bytes:number|null){if(bytes===null)return "-";if(bytes<1024)return `${bytes} B`;if(bytes<1024**2)return `${(bytes/1024).toFixed(bytes<10240?1:0)} KB`;if(bytes<1024**3)return `${(bytes/1024**2).toFixed(bytes<10*1024**2?1:0)} MB`;return `${(bytes/1024**3).toFixed(1)} GB`;}

export function FilesBrowserPage({page,notify,permissions}:{page:PageKey;notify:Notify;permissions:readonly Permission[]}){
  const[currentPath,setCurrentPath]=useState(""),[search,setSearch]=useState(""),[typeFilter,setTypeFilter]=useState("全部"),[drawer,setDrawer]=useState<Drawer|null>(null),[draftName,setDraftName]=useState("new-folder"),[operationError,setOperationError]=useState(""),[pending,setPending]=useState(false),[uploading,setUploading]=useState(false);
  const uploadRef=useRef<HTMLInputElement>(null),canManage=permissions.includes("files:manage"),{data,loading,error,reload}=useFilesData(currentPath,setCurrentPath),rows=data?.entries??[];
  const crumbs=currentPath.split("/").filter(Boolean),visibleRows=rows.filter((row)=>(typeFilter==="全部"||kindLabel[row.kind]===typeFilter)&&(!search.trim()||row.name.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())));
  const run=async(action:()=>Promise<{message:string}>)=>{setPending(true);setOperationError("");try{const result=await action();notify(result.message,drawer?.type==="delete"?"warning":"success");setDrawer(null);await reload();}catch(reason){setOperationError(reason instanceof Error?reason.message:"操作失败");}finally{setPending(false);}};
  const entryIcon=(kind:typeof rows[number]["kind"])=>kind==="directory"?Folder:kind==="symlink"?Link2:FileBox;
  return <ModulePageShell title={resolvePageMeta(page).title} subtitle="浏览和管理服务器配置根目录中的真实文件。" page={page}
    viewContext={{eyebrow:"文件 / 站点目录",title:currentPath||"正在定位文件根目录",chips:[loading?"正在读取":`${rows.length} 个项目`,data?.writable?"可写":"只读",data?`采集于 ${formatBackendDateTime(data.collectedAt)}`:"等待采集"]}}
    actions={<><input ref={uploadRef} className="sr-only" type="file" aria-label="选择上传文件" onChange={async(event)=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;setUploading(true);try{const result=await uploadFile(currentPath,file);notify(result.message);await reload();}catch(reason){notify(reason instanceof Error?reason.message:"文件上传失败","danger");}finally{setUploading(false);}}}/><button className="ghost" type="button" disabled={!canManage||uploading||!data?.writable} onClick={()=>uploadRef.current?.click()}>{uploading?<LoaderCircle className="spin" size={15}/>:<CloudUpload size={15}/>} 上传</button><button className="primary" type="button" disabled={!canManage||!data?.writable} onClick={()=>{setDraftName("new-folder");setOperationError("");setDrawer({type:"folder"});}}><Plus size={15}/> 创建文件夹</button></>}
    filters={<><ModuleSearch value={search} placeholder="搜索文件名" onChange={setSearch}/><FieldSelect label="类型" value={typeFilter} options={["全部","文件夹","文件","链接"]} onChange={setTypeFilter}/></>}
    side={drawer?.type==="folder"?<DetailDrawer title="创建文件夹" subtitle={currentPath} className="file-editor-drawer" modal onClose={()=>setDrawer(null)} actions={<><button className="ghost" type="button" onClick={()=>setDrawer(null)}>取消</button><button className="primary" type="button" disabled={pending} onClick={()=>void run(()=>createDirectory(currentPath,draftName))}>{pending?"正在创建":"创建"}</button></>}><FormLine label="文件夹名" required value={draftName} onChange={setDraftName}/>{operationError&&<p className="files-operation-error" role="alert">{operationError}</p>}</DetailDrawer>
      :drawer?.type==="rename"?<DetailDrawer title="重命名" subtitle={drawer.name} className="file-editor-drawer" modal onClose={()=>setDrawer(null)} actions={<><button className="ghost" type="button" onClick={()=>setDrawer(null)}>取消</button><button className="primary" type="button" disabled={pending} onClick={()=>void run(()=>renameFile(drawer.path,draftName))}>{pending?"正在保存":"保存"}</button></>}><FormLine label="新名称" required value={draftName} onChange={setDraftName}/>{operationError&&<p className="files-operation-error" role="alert">{operationError}</p>}</DetailDrawer>
      :drawer?.type==="delete"?<DetailDrawer title="移入回收站" subtitle={drawer.name} className="file-delete-dialog" modal onClose={()=>setDrawer(null)} actions={<><button className="ghost" type="button" onClick={()=>setDrawer(null)}>取消</button><button className="files-destructive" type="button" disabled={pending} aria-label={`确认将 ${drawer.name} 移入回收站`} onClick={()=>void run(()=>deleteFile(drawer.path))}><Trash2 size={15}/>{pending?"正在移动":"确认移入"}</button></>}><div className="file-delete-summary"><Trash2 size={20}/><div><strong>确认移动这个{kindLabel[drawer.kind]}？</strong><p>项目将从当前目录移入服务器隔离回收区。</p></div></div><dl className="file-delete-facts"><div><dt>名称</dt><dd>{drawer.name}</dd></div><div><dt>原路径</dt><dd><code>{drawer.path}</code></dd></div></dl>{operationError&&<p className="files-operation-error" role="alert">{operationError}</p>}</DetailDrawer>:null} sideModal={Boolean(drawer)}>
    <div className="file-breadcrumbs"><button className="file-parent-button" type="button" disabled={!data?.parentPath||loading} onClick={()=>data?.parentPath&&setCurrentPath(data.parentPath)}>上级</button><span aria-hidden="true"><ChevronRight size={14}/></span>{crumbs.map((crumb,index)=>{const nextPath=`/${crumbs.slice(0,index+1).join("/")}`,active=nextPath===currentPath;return <span className="file-breadcrumb-item" key={nextPath}><ChevronRight size={14} aria-hidden="true"/><button type="button" className={active?"active":""} aria-current={active?"page":undefined} onClick={()=>setCurrentPath(nextPath)}>{crumb}</button></span>;})}</div>
    {error?<div className="files-load-state" role="alert"><span>{error}</span><button className="ghost" type="button" onClick={()=>void reload()}><RefreshCw size={15}/>重试</button></div>:loading&&!data?<div className="files-load-state" role="status"><LoaderCircle className="spin" size={18}/><span>正在读取目录</span></div>:<DataTable columns={[
      {key:"name",label:"名称",width:"260px",render:(row)=>{const Icon=entryIcon(row.kind);return row.kind==="directory"?<button className="file-link file-name" type="button" title={row.name} onClick={()=>setCurrentPath(row.path)}><Icon size={15}/><b>{row.name}</b></button>:<span className="file-name" title={row.name}><Icon size={15}/><b>{row.name}</b></span>;}},
      {key:"type",label:"类型",width:"86px",render:(row)=><span className="pill blue">{kindLabel[row.kind]}</span>},{key:"size",label:"大小",sortValue:(row)=>row.sizeBytes,render:(row)=>size(row.sizeBytes)},{key:"modified",label:"修改时间",render:(row)=>formatBackendDateTime(row.modifiedAt)},{key:"owner",label:"所有者",render:(row)=>row.owner},{key:"ops",label:"操作",width:"170px",render:(row)=>{const cannotRename=!canManage||!data?.writable||row.kind!=="file",cannotDelete=!canManage||!data?.writable||row.kind==="symlink";return <span className="table-actions file-row-actions"><button type="button" disabled={cannotRename} title={row.kind!=="file"?"当前仅支持重命名普通文件":undefined} aria-label={`重命名 ${row.name}`} onClick={()=>{setDraftName(row.name);setOperationError("");setDrawer({type:"rename",path:row.path,name:row.name,kind:row.kind});}}><Pencil size={14}/>重命名</button><button type="button" disabled={cannotDelete} title={row.kind==="symlink"?"不允许删除符号链接":undefined} aria-label={`删除 ${row.name} 到回收站`} onClick={()=>{setOperationError("");setDrawer({type:"delete",path:row.path,name:row.name,kind:row.kind});}}><Trash2 size={14}/>删除</button></span>;}},
    ]} rows={visibleRows} emptyText="当前路径没有匹配文件" getRowKey={(row)=>row.id} mobileCard={(row)=>{const Icon=entryIcon(row.kind);return <><div className="module-card-head">{row.kind==="directory"?<button className="module-row-link" type="button" onClick={()=>setCurrentPath(row.path)}><Icon size={15}/><b>{row.name}</b></button>:<span className="module-card-title"><Icon size={15}/><b>{row.name}</b></span>}<span className="pill blue">{kindLabel[row.kind]}</span></div><code className="module-card-code">{row.path}</code><div className="module-card-meta"><span><b>大小</b><em>{size(row.sizeBytes)}</em></span><span><b>修改</b><em>{formatBackendDateTime(row.modifiedAt)}</em></span><span><b>所有者</b><em>{row.owner}</em></span></div></>;}}/>}
  </ModulePageShell>;
}
