import { Activity, AlertTriangle, CheckCircle2, Clock3, CloudOff, Database, Download, FileSearch, Gauge, Play, Server, Wrench } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { DatabaseOperationPlan, DatabaseSlowQueriesPayload, DatabaseSlowQueryRecord, Permission } from "@stackpilot/contracts";
import { createDatabaseOperationPlan, explainDatabaseQuery, resolveDatabaseQuery } from "../api/databasesApi";
import { resolvePageMeta } from "../app/navigation";
import { ModulePageShell } from "../components/layout/ModulePageShell";
import { MetricTile, ModuleSearch, PanelCard } from "../components/ui/Cards";
import { DataTable } from "../components/ui/DataTable";
import { DetailDrawer } from "../components/ui/DetailDrawer";
import { FieldSelect } from "../components/ui/FormControls";
import { DatabasePlanDialog } from "../features/databases/DatabasePlanDialog";
import { databaseIdempotencyKey, waitForDatabaseOperation } from "../features/databases/operationClient";
import { useDatabaseSlowQueries } from "../features/databases/useDatabaseSlowQueries";
import type { Notify, PageKey, Tone } from "../types/app";
import { formatBackendDateTime } from "../utils/time";

type RiskLabel = "高" | "中" | "低";
function DatabaseSlowQueriesPage({ page, notify, initialPayload = null, permissions = [] }: { page: PageKey; notify: Notify; initialPayload?: DatabaseSlowQueriesPayload | null; permissions?: Permission[] }) {
  const [range, setRange] = useState<"24h" | "7d">("24h"); const { data: payload, loading, error, backgroundError, retry, refresh } = useDatabaseSlowQueries(range, initialPayload);
  const [search, setSearch] = useState(""); const [databaseFilter, setDatabaseFilter] = useState("全部"); const [levelFilter, setLevelFilter] = useState("全部");
  const [drawerId, setDrawerId] = useState<string | null>(null); const [busyAction, setBusyAction] = useState<string | null>(null); const [explain, setExplain] = useState<string | null>(null);
  const [table, setTable] = useState(""); const [columns, setColumns] = useState(""); const [indexPlan, setIndexPlan] = useState<DatabaseOperationPlan | null>(null);
  const queries = useMemo(() => payload?.queries ?? [], [payload]); const instances = payload?.instances ?? []; const available = payload !== null && payload.collectionStatus !== "unavailable";
  const historyUnavailable = instances.filter((instance) => instance.historicalSlowQueriesAvailable === false).length;
  const collectionMessage = backgroundError ? `后台刷新失败，保留上次数据：${backgroundError}` : payload?.warnings[0]
    ?? (historyUnavailable === instances.length && instances.length > 0 ? "历史慢查询不可用，仅展示当前长查询"
      : historyUnavailable > 0 ? "部分实例历史慢查询不可用，仅展示其当前长查询" : "数据来自节点采集快照");
  const selectedQuery = drawerId ? queries.find((query) => query.id === drawerId) ?? null : null;
  useEffect(() => { if (!drawerId || !payload || queries.some((query) => query.id === drawerId)) return; let active = true; queueMicrotask(() => { if (active) setDrawerId(null); }); return () => { active = false; }; }, [drawerId, payload, queries]);
  const databaseOptions = ["全部", ...new Set([...queries.map((query) => query.database), ...instances.map((instance) => instance.name)])];
  const filtered = queries.filter((query) => { const keyword = search.trim().toLowerCase(); return (!keyword || `${query.database} ${query.fingerprint} ${query.sql ?? ""} ${query.owner ?? ""}`.toLowerCase().includes(keyword)) && (databaseFilter === "全部" || query.database === databaseFilter) && (levelFilter === "全部" || riskLabel(query.risk) === levelFilter); });
  const explainQuery = async (query: DatabaseSlowQueryRecord) => { setBusyAction("explain"); setExplain(null); try { const operation = await waitForDatabaseOperation((await explainDatabaseQuery(query.id, databaseIdempotencyKey("explain"))).operation); if (operation.result?.kind !== "explain") throw new Error("后端未返回 Explain 结果"); setExplain(operation.result.plan); } catch (caught) { notify(caught instanceof Error ? caught.message : "Explain 失败", "danger"); } finally { setBusyAction(null); } };
  const resolveQuery = async (query: DatabaseSlowQueryRecord) => { setBusyAction("resolve"); try { await resolveDatabaseQuery(query.id, "操作员已在慢查询中心确认处置"); notify("慢查询已标记为已处理", "success"); setDrawerId(null); await refresh(); } catch (caught) { notify(caught instanceof Error ? caught.message : "慢查询处置失败", "danger"); } finally { setBusyAction(null); } };
  const prepareIndex = async (query: DatabaseSlowQueryRecord) => { setBusyAction("index"); try { const names = columns.split(",").map((value) => value.trim()).filter(Boolean); setIndexPlan((await createDatabaseOperationPlan({ kind: "create-index", instanceId: query.instanceId, queryId: query.id, table: table.trim(), columns: names })).plan); } catch (caught) { notify(caught instanceof Error ? caught.message : "无法创建索引计划", "danger"); } finally { setBusyAction(null); } };
  const exportCsv = () => downloadCsv("database-slow-queries.csv", [["SQL 指纹", "数据库", "SQL", "耗时毫秒", "风险", "状态", "用户", "开始时间"], ...filtered.map((query) => [query.fingerprint, query.database, query.sql ?? "", String(query.durationMs), riskLabel(query.risk), stateLabel(query.state), query.owner ?? "", query.startedAt])]);
  return <><ModulePageShell title={resolvePageMeta(page).title} subtitle={`查询时间范围 ${range} · 阈值 ${payload ? duration(payload.thresholdMs) : "暂不可用"}`} page={page}
    viewContext={{ eyebrow: "数据库 / 慢查询", title: "慢查询中心", chips: available ? [`查询 ${queries.length}`, `实例 ${instances.length}`] : ["统计暂不可用"] }}
    actions={<button className="ghost" type="button" disabled={!filtered.length} onClick={exportCsv}><Download size={15} /> 导出</button>}
    filters={<><ModuleSearch value={search} placeholder="搜索 SQL、指纹、数据库或用户" onChange={setSearch} /><FieldSelect label="范围" value={range} options={["24h", "7d"]} onChange={(value) => setRange(value as "24h" | "7d")} /><FieldSelect label="数据库" value={databaseFilter} options={databaseOptions} onChange={setDatabaseFilter} /><FieldSelect label="风险" value={levelFilter} options={["全部", "高", "中", "低"]} onChange={setLevelFilter} /></>}
    metrics={<><MetricTile icon={Activity} label="慢查询" value={available ? `${queries.length}` : "暂不可用"} tone="blue" /><MetricTile icon={Clock3} label="最长耗时" value={available && queries.length ? duration(Math.max(...queries.map((query) => query.durationMs))) : "暂不可用"} tone="purple" /><MetricTile icon={Database} label="受影响数据库" value={available ? `${new Set(queries.map((query) => query.database)).size}` : "暂不可用"} tone="green" /><MetricTile icon={AlertTriangle} label="高风险" value={available ? `${queries.filter((query) => query.risk === "high").length}` : "暂不可用"} tone="orange" /></>}>
    {loading && !payload && <span className="sr-only" role="status">正在读取慢查询</span>}{error && !payload && <div className="overview-error-state"><CloudOff size={18} /><span>{error}</span><button type="button" onClick={() => void retry()}>重试</button></div>}
    <div className="slow-freshness"><Clock3 size={20} /><div><strong>采集时间 {formatBackendDateTime(payload?.collectedAt, "暂不可用")}</strong><span>{collectionMessage}</span></div></div>
    <DataTable columns={[{ key: "fingerprint", label: "SQL 指纹", width: "190px", render: (query) => <button className="module-row-link slow-fingerprint" type="button" title={query.fingerprint} aria-label={`查看慢查询 ${query.fingerprint}`} onClick={() => { setDrawerId(query.id); setExplain(null); }}><FileSearch size={16} /><b>{query.fingerprint}</b></button> }, { key: "database", label: "数据库", width: "150px", render: (query) => <span title={query.database}>{query.database}</span> }, { key: "sql", label: "SQL 摘要", render: (query) => <code className="slow-sql-summary" title={query.sql ?? undefined}>{query.sql ?? "无权查看完整 SQL"}</code> }, { key: "duration", label: "耗时", width: "105px", render: (query) => duration(query.durationMs) }, { key: "risk", label: "风险", width: "100px", render: (query) => <RiskBadge risk={query.risk} /> }, { key: "state", label: "状态", width: "100px", render: (query) => stateLabel(query.state) }]} rows={filtered} emptyText={available ? "当前时间范围没有慢查询" : "慢查询统计暂不可用"} getRowKey={(query) => query.id} />
    <PanelCard title="数据库采集状态"><div className="slow-instance-list">{instances.map((instance) => <article key={instance.id}><span className="slow-list-icon blue"><Server size={20} /></span><div><strong title={instance.name}>{instance.name}</strong><span>{instance.engine} · {instance.host}:{instance.port}</span><small><Clock3 size={12} />{formatBackendDateTime(instance.collectedAt)}</small></div><span className={`slow-status-badge ${instance.slowQueryCount ? "orange" : "green"}`}>{instance.slowQueryCount ?? 0} 条</span></article>)}</div></PanelCard>
  </ModulePageShell>{selectedQuery && <DetailDrawer title="慢查询详情" subtitle={selectedQuery.fingerprint} modal onClose={() => setDrawerId(null)} actions={permissions.includes("databases:operate") ? <><button className="ghost" type="button" disabled={Boolean(busyAction)} onClick={() => void explainQuery(selectedQuery)}><Play size={14} />Explain</button><button className="ghost" type="button" disabled={Boolean(busyAction)} onClick={() => void resolveQuery(selectedQuery)}><CheckCircle2 size={14} />标记处理</button></> : undefined}><div className="slow-query-drawer"><div className="slow-drawer-summary"><span className="slow-list-icon blue"><Database size={18} /></span><div><strong>{selectedQuery.database}</strong><span>{selectedQuery.fingerprint}</span></div><RiskBadge risk={selectedQuery.risk} /></div><dl><div><dt>状态</dt><dd>{stateLabel(selectedQuery.state)}</dd></div><div><dt>耗时</dt><dd>{duration(selectedQuery.durationMs)}</dd></div><div><dt>P95 / 调用</dt><dd>{selectedQuery.p95Ms === null ? "暂不可用" : duration(selectedQuery.p95Ms)} / {selectedQuery.calls ?? "暂不可用"}</dd></div><div><dt>用户</dt><dd>{selectedQuery.owner ?? "暂不可用"}</dd></div></dl><section><h3>SQL</h3><code>{selectedQuery.sql ?? "当前角色没有 databases:sql:read 权限"}</code></section>{explain && <section><h3>Explain 结果</h3><code>{explain}</code></section>}{permissions.includes("databases:operate") && selectedQuery.sql && <section><h3><Wrench size={15} /> 创建固定索引</h3><div className="database-create-form"><label><span>表名</span><input value={table} onChange={(e) => setTable(e.target.value)} /></label><label><span>列名（逗号分隔）</span><input value={columns} onChange={(e) => setColumns(e.target.value)} /></label></div><button className="ghost" type="button" disabled={!table.trim() || !columns.trim() || Boolean(busyAction)} onClick={() => void prepareIndex(selectedQuery)}>生成索引确认计划</button></section>}</div></DetailDrawer>}{indexPlan && <DatabasePlanDialog plan={indexPlan} onClose={() => setIndexPlan(null)} onComplete={() => { setIndexPlan(null); notify("索引创建已完成", "success"); void refresh(); }} />}</>;
}
function RiskBadge({ risk }: { risk: DatabaseSlowQueryRecord["risk"] }) { const Icon = risk === "high" ? AlertTriangle : risk === "medium" ? Gauge : CheckCircle2; return <span className={`slow-status-badge ${riskTone(risk)}`}><Icon size={13} />{riskLabel(risk)}风险</span>; }
function duration(ms: number) { return ms >= 60_000 ? `${(ms / 60_000).toFixed(1)} 分` : ms >= 1_000 ? `${(ms / 1_000).toFixed(2)} 秒` : `${ms}ms`; }
function riskLabel(risk: DatabaseSlowQueryRecord["risk"]): RiskLabel { return risk === "high" ? "高" : risk === "medium" ? "中" : "低"; }
function stateLabel(state: DatabaseSlowQueryRecord["state"]) { return state === "waiting" ? "等待中" : state === "resolved" ? "已处理" : "执行中"; }
function riskTone(risk: DatabaseSlowQueryRecord["risk"]): Tone { return risk === "high" ? "orange" : risk === "medium" ? "blue" : "green"; }
function downloadCsv(name: string, rows: string[][]) { const csv = rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\r\n"); const url = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }
export { DatabaseSlowQueriesPage };
