import { ArchiveRestore, CalendarClock, CircleAlert, Clock3, Download, HardDrive, Play, Plus, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import type { BusinessDatabaseBackupPlan, DatabaseOperationPlan, DatabaseRestorePoint, Permission } from "@stackpilot/contracts";
import { createBackupPlan, createDatabaseOperationPlan, fetchBusinessDatabaseBackups, fetchDatabases, runBackupPlan, updateBackupPlan } from "../api/databasesApi";
import { resolvePageMeta } from "../app/navigation";
import { ModulePageShell } from "../components/layout/ModulePageShell";
import { MetricTile, ModuleSearch } from "../components/ui/Cards";
import { ConfirmDialog } from "../components/ui/ConfirmDialog";
import { DataTable } from "../components/ui/DataTable";
import { DetailDrawer } from "../components/ui/DetailDrawer";
import { DatabasePlanDialog } from "../features/databases/DatabasePlanDialog";
import { databaseIdempotencyKey } from "../features/databases/operationClient";
import { usePollingResource } from "../hooks/usePollingResource";
import type { Notify, PageKey } from "../types/app";
import { formatBackendDateTime } from "../utils/time";

type BackupData = { backups: Awaited<ReturnType<typeof fetchBusinessDatabaseBackups>>; instances: Awaited<ReturnType<typeof fetchDatabases>>["instances"] };

function DatabaseBackupsPage({ page, notify, permissions = [] }: { page: PageKey; notify: Notify; permissions?: Permission[] }) {
  const { data, loading, error, backgroundError, retry, refresh } = usePollingResource<BackupData>(async (signal) => {
    const [backups, inventory] = await Promise.all([fetchBusinessDatabaseBackups(signal), fetchDatabases(signal)]); return { backups, instances: inventory.instances };
  });
  const [search, setSearch] = useState(""); const [createOpen, setCreateOpen] = useState(false); const [selectedPointId, setSelectedPointId] = useState<string | null>(null);
  const [restorePlan, setRestorePlan] = useState<DatabaseOperationPlan | null>(null); const [busyId, setBusyId] = useState<string | null>(null);
  const plans = data?.backups.plans ?? [], jobs = data?.backups.jobs ?? [], points = data?.backups.restorePoints ?? [];
  const instanceById = useMemo(() => new Map((data?.instances ?? []).map((row) => [row.id, row])), [data]);
  const keyword = search.trim().toLowerCase();
  const filteredPoints = points.filter((point) => { const instance = instanceById.get(point.instanceId); return !keyword || `${instance?.name ?? point.instanceId} ${point.checksum}`.toLowerCase().includes(keyword); });
  const selectedPoint = points.find((point) => point.id === selectedPointId) ?? null;
  const run = async (plan: BusinessDatabaseBackupPlan) => { setBusyId(plan.id); try { await runBackupPlan(plan.id, databaseIdempotencyKey("backup")); notify("备份任务已提交", "success"); await refresh(); } catch (caught) { notify(caught instanceof Error ? caught.message : "备份任务提交失败", "danger"); } finally { setBusyId(null); } };
  const toggle = async (plan: BusinessDatabaseBackupPlan) => { setBusyId(plan.id); try { await updateBackupPlan(plan.id, { enabled: !plan.enabled, version: plan.version }); notify(plan.enabled ? "备份计划已停用" : "备份计划已启用", "success"); await refresh(); } catch (caught) { notify(caught instanceof Error ? caught.message : "备份计划更新失败", "danger"); } finally { setBusyId(null); } };
  const prepareRestore = async (point: DatabaseRestorePoint) => { setBusyId(point.id); try { setRestorePlan((await createDatabaseOperationPlan({ kind: "restore", instanceId: point.instanceId, restorePointId: point.id })).plan); } catch (caught) { notify(caught instanceof Error ? caught.message : "无法创建恢复计划", "danger"); } finally { setBusyId(null); } };
  const exportCsv = () => downloadCsv("database-restore-points.csv", [["实例", "创建时间", "大小", "SHA-256", "数据库版本", "校验时间"], ...filteredPoints.map((point) => [instanceById.get(point.instanceId)?.name ?? point.instanceId, point.createdAt, String(point.sizeBytes), point.checksum, point.databaseVersion, point.verifiedAt ?? ""])]);
  return <><ModulePageShell title={resolvePageMeta(page).title} subtitle="业务数据库的本地逻辑备份计划、任务与恢复点" page={page} className="module-page-databases-backups"
    viewContext={{ eyebrow: "数据库 / 备份恢复", title: "业务数据库备份", chips: [`计划 ${plans.length}`, `任务 ${jobs.length}`, `恢复点 ${points.length}`] }}
    actions={<><button className="ghost" type="button" disabled={!filteredPoints.length} onClick={exportCsv}><Download size={15} /> 导出</button>{permissions.includes("databases:backup") && <button className="primary" type="button" disabled={!data?.instances.length} onClick={() => setCreateOpen(true)}><Plus size={15} /> 新建备份计划</button>}</>}
    filters={<ModuleSearch value={search} placeholder="搜索实例或校验和" onChange={setSearch} />}
    metrics={<><MetricTile icon={CalendarClock} label="备份计划" value={data ? `${plans.length}` : "暂不可用"} tone="blue" /><MetricTile icon={Clock3} label="执行中任务" value={data ? `${jobs.filter((job) => job.status === "queued" || job.status === "running").length}` : "暂不可用"} tone="orange" /><MetricTile icon={ShieldCheck} label="已验证恢复点" value={data ? `${points.filter((point) => point.verifiedAt).length}` : "暂不可用"} tone="green" /><MetricTile icon={HardDrive} label="恢复点容量" value={data ? formatBytes(points.reduce((sum, point) => sum + point.sizeBytes, 0)) : "暂不可用"} tone="purple" /></>}>
    {loading && !data && <p role="status" className="backup-page-state">正在读取业务数据库备份...</p>}
    {error && !data && <div className="overview-error-state"><CircleAlert size={18} /><span>{error}</span><button type="button" onClick={() => void retry()}>重试</button></div>}
    {data && <><p className="database-collection-note"><Clock3 size={15} />采集时间 {formatBackendDateTime(data.backups.collectedAt)}{backgroundError ? ` · 后台刷新失败，保留上次数据：${backgroundError}` : data.backups.warnings[0] ? ` · ${data.backups.warnings[0]}` : ""}</p>
      <section className="database-backup-section"><h2>备份计划</h2>{plans.length ? <div className="database-plan-list">{plans.map((plan) => <article key={plan.id}><div><b>{plan.name}</b><span>{instanceById.get(plan.instanceId)?.name ?? plan.instanceId}</span><small>{plan.cron} · 保留 {plan.retentionCount} 份 · {plan.enabled ? "已启用" : "已停用"}</small></div>{permissions.includes("databases:backup") && <div><button className="ghost small" type="button" disabled={busyId === plan.id || !plan.enabled} onClick={() => void run(plan)}><Play size={14} />立即备份</button><button className="ghost small" type="button" disabled={busyId === plan.id} onClick={() => void toggle(plan)}>{plan.enabled ? "停用" : "启用"}</button></div>}</article>)}</div> : <p className="module-card-empty">尚未创建业务数据库备份计划</p>}</section>
      <section className="database-backup-section"><h2>最近任务</h2><DataTable columns={[{ key: "instance", label: "实例", render: (job) => instanceById.get(job.instanceId)?.name ?? job.instanceId }, { key: "status", label: "状态", width: "120px", render: (job) => operationStatus(job.status) }, { key: "started", label: "开始时间", width: "170px", render: (job) => formatBackendDateTime(job.startedAt) }, { key: "size", label: "大小", width: "110px", render: (job) => formatBytes(job.sizeBytes) }, { key: "error", label: "结果", render: (job) => job.errorCode ?? (job.status === "succeeded" ? "备份完成" : "等待节点执行") }]} rows={jobs} getRowKey={(job) => job.id} emptyText="尚无真实备份任务" /></section>
      <section className="database-backup-section"><h2>恢复点</h2><DataTable columns={[{ key: "instance", label: "实例", render: (point) => <button className="module-row-link" type="button" onClick={() => setSelectedPointId(point.id)}>{instanceById.get(point.instanceId)?.name ?? point.instanceId}</button> }, { key: "created", label: "创建时间", width: "170px", render: (point) => formatBackendDateTime(point.createdAt) }, { key: "size", label: "大小", width: "110px", render: (point) => formatBytes(point.sizeBytes) }, { key: "checksum", label: "SHA-256", render: (point) => <code title={point.checksum}>{point.checksum}</code> }, { key: "verified", label: "验证", width: "120px", render: (point) => point.verifiedAt ? "已验证" : "待验证" }]} rows={filteredPoints} getRowKey={(point) => point.id} emptyText={points.length ? "没有匹配的恢复点" : "尚无真实恢复点"} /></section></>}
  </ModulePageShell>{createOpen && data && <BackupPlanDialog instances={data.instances} onClose={() => setCreateOpen(false)} onComplete={() => { setCreateOpen(false); notify("备份计划已创建", "success"); void refresh(); }} />}{selectedPoint && <DetailDrawer title="恢复点详情" subtitle={instanceById.get(selectedPoint.instanceId)?.name ?? selectedPoint.instanceId} modal onClose={() => setSelectedPointId(null)} actions={permissions.includes("databases:restore") && instanceById.get(selectedPoint.instanceId)?.managed ? <button className="primary" type="button" disabled={busyId === selectedPoint.id} onClick={() => void prepareRestore(selectedPoint)}><ArchiveRestore size={15} />原地恢复</button> : undefined}><div className="backup-drawer-body"><dl><div><dt>创建时间</dt><dd>{formatBackendDateTime(selectedPoint.createdAt)}</dd></div><div><dt>大小</dt><dd>{formatBytes(selectedPoint.sizeBytes)}</dd></div><div><dt>数据库版本</dt><dd>{selectedPoint.databaseVersion}</dd></div><div><dt>Manifest</dt><dd>v{selectedPoint.manifestVersion}</dd></div><div><dt>SHA-256</dt><dd><code>{selectedPoint.checksum}</code></dd></div></dl></div></DetailDrawer>}{restorePlan && <DatabasePlanDialog plan={restorePlan} onClose={() => setRestorePlan(null)} onComplete={() => { setRestorePlan(null); setSelectedPointId(null); notify("数据库恢复已完成", "success"); void refresh(); }} />}</>;
}

function BackupPlanDialog({ instances, onClose, onComplete }: { instances: BackupData["instances"]; onClose: () => void; onComplete: () => void }) {
  const [instanceId, setInstanceId] = useState(instances[0]?.id ?? ""); const [name, setName] = useState(""); const [cron, setCron] = useState("0 2 * * *"); const [retentionCount, setRetentionCount] = useState(7); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async () => { setBusy(true); setError(null); try { await createBackupPlan({ instanceId, name, cron, retentionCount, enabled: true }); onComplete(); } catch (caught) { setError(caught instanceof Error ? caught.message : "备份计划创建失败"); } finally { setBusy(false); } };
  return <ConfirmDialog title="新建业务数据库备份计划" message="计划由目标节点本地调度，Controller 断线时仍可执行。" confirmLabel="创建计划" busy={busy} confirmDisabled={!instanceId || !name || !cron} onClose={onClose} onConfirm={() => void submit()}><div className="database-create-form"><label><span>实例</span><select value={instanceId} onChange={(e) => setInstanceId(e.target.value)}>{instances.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label><span>计划名称</span><input value={name} onChange={(e) => setName(e.target.value)} /></label><label><span>Cron</span><input value={cron} onChange={(e) => setCron(e.target.value)} /></label><label><span>保留份数</span><input type="number" min="1" max="30" value={retentionCount} onChange={(e) => setRetentionCount(Number(e.target.value))} /></label></div>{error && <p className="form-error" role="alert">{error}</p>}</ConfirmDialog>;
}
function operationStatus(value: string) { return ({ queued: "已排队", running: "执行中", succeeded: "成功", failed: "失败", cancelled: "已取消" } as Record<string, string>)[value] ?? value; }
function formatBytes(value: number | null) { if (value === null) return "暂不可用"; const units = ["B", "KB", "MB", "GB", "TB"]; let amount = value, index = 0; while (amount >= 1024 && index < units.length - 1) { amount /= 1024; index += 1; } return `${amount.toFixed(index < 2 ? 0 : 1)} ${units[index]}`; }
function downloadCsv(name: string, rows: string[][]) { const csv = rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\r\n"); const url = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }
export { DatabaseBackupsPage };
