import type { CreateRemoteTaskRequest, Permission } from "@stackpilot/contracts";
import { Clock3, KeyRound, Shield, TerminalSquare } from "lucide-react";
import { useMemo, useState } from "react";
import { reauthenticate } from "../api/identityApi";
import { terminalPagePreset } from "../app/pagePresets";
import { resolvePageMeta } from "../app/navigation";
import { ModulePageShell } from "../components/layout/ModulePageShell";
import { MetricTile, ModuleSearch } from "../components/ui/Cards";
import { ConfirmDialog } from "../components/ui/ConfirmDialog";
import { DetailDrawer } from "../components/ui/DetailDrawer";
import { FieldSelect } from "../components/ui/FormControls";
import { LiveConsole, LiveHistoryList, LiveSessionList } from "../features/terminal/LiveTerminalWorkspace";
import { commandCapability, commandRequest, freshness, supportsCommand, terminalTasks, toHistory, toSessions } from "../features/terminal/liveModel";
import type { LiveTerminalHistory } from "../features/terminal/liveTypes";
import { TerminalSnippetsWorkspace } from "../features/terminal/TerminalSnippetsWorkspace";
import { TerminalSessionDrawer } from "../features/terminal/TerminalSessionDrawer";
import { useLiveTerminal } from "../features/terminal/useLiveTerminal";
import type { Notify, PageKey } from "../types/app";

const defaultPermissions: Permission[] = ["overview:read", "nodes:read", "tasks:read", "tasks:create", "terminal:read", "terminal:execute"];
type TerminalPanel = "sessions" | "snippets" | "history";

function TerminalPage({ page, notify, permissions = defaultPermissions }: { page: PageKey; notify: Notify; permissions?: Permission[] }) {
  const mode = terminalPagePreset(page).panel as TerminalPanel;
  if (mode === "snippets") return <TerminalSnippetsWorkspace notify={notify} permissions={permissions} />;
  return <TerminalSessionWorkspace page={page} notify={notify} permissions={permissions} mode={mode} />;
}

function TerminalSessionWorkspace({ page, notify, permissions, mode }: { page: PageKey; notify: Notify; permissions: Permission[]; mode: Exclude<TerminalPanel, "snippets"> }) {
  const data = useLiveTerminal(permissions); const [selectedId, setSelectedId] = useState(""); const [command, setCommand] = useState(""); const [search, setSearch] = useState(""); const [filters, setFilters] = useState({ sessions: "全部", history: "全部" }); const [detailSessionId, setDetailSessionId] = useState<string | null>(null); const [historyId, setHistoryId] = useState<string | null>(null); const [pending, setPending] = useState<{ command: string; nodeId: string; request: CreateRemoteTaskRequest } | null>(null); const [password, setPassword] = useState(""); const [submitError, setSubmitError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false); const filter = filters[mode];
  const tasks = useMemo(() => terminalTasks(data.tasks), [data.tasks]); const sessions = useMemo(() => toSessions(data.nodes, data.hosts, tasks), [data.hosts, data.nodes, tasks]); const history = useMemo(() => tasks.map((task) => toHistory(task, data.nodes.find((node) => node.nodeId === task.targetNodeId))), [data.nodes, tasks]); const selected = sessions.find((row) => row.id === selectedId) ?? sessions.find((row) => row.status === "connected") ?? sessions[0] ?? null; const selectedNode = data.nodes.find((node) => node.nodeId === selected?.id); const detailSession = sessions.find((row) => row.id === detailSessionId) ?? null; const detailHistory = history.find((row) => row.id === historyId) ?? null; const canExecute = permissions.includes("tasks:create");
  const view = search.trim().toLowerCase(); const sessionRows = sessions.filter((row) => (!view || `${row.host} ${row.ip}`.toLowerCase().includes(view)) && (filter === "全部" || row.status === filter)); const historyRows = history.filter((row) => (!view || `${row.command} ${row.host} ${row.output}`.toLowerCase().includes(view)) && (filter === "全部" || row.status === filter)); const logs = selected ? history.filter((row) => row.nodeId === selected.id).flatMap((row) => [`$ ${row.command}`, ...row.output.split("\n")]) : [];
  const requestExecution = (value: string, nodeId = selected?.id) => { const next = value.trim(); const target = sessions.find((row) => row.id === nodeId); const targetNode = data.nodes.find((node) => node.nodeId === nodeId); if (!next || !nodeId) return; if (!target || target.status !== "connected") return notify("目标 Agent 当前离线", "danger"); if (!canExecute) return notify("当前账号没有任务执行权限", "danger"); const request = commandRequest(next); if (!request) return notify("仅支持 df -h、uptime、top 和 systemctl status <服务>", "danger"); if (!supportsCommand(targetNode, next)) return notify("目标 Agent 未声明或未获授权执行该受控能力", "danger"); setSubmitError(null); setPassword(""); setPending({ command: next, nodeId, request }); };
  const submit = async () => { if (!pending) return; const currentNode = data.nodes.find((node) => node.nodeId === pending.nodeId); if (!supportsCommand(currentNode, pending.command)) { setSubmitError("目标 Agent 能力已变更，请重新选择命令"); return; } setSubmitting(true); try { const proof = await reauthenticate(password); await data.create(pending.nodeId, pending.request, proof.proof); setCommand(""); setPending(null); notify("真实任务已提交，等待 Agent 返回结果", "success"); } catch (reason) { setSubmitError(reason instanceof Error ? reason.message : "任务提交失败"); } finally { setSubmitting(false); } };
  const copy = (value: string, message = "内容已复制") => void navigator.clipboard.writeText(value).then(() => notify(message, "info")).catch(() => notify("复制失败，请检查浏览器权限", "danger")); const rerun = (row: LiveTerminalHistory) => requestExecution(row.command, row.nodeId); const options = mode === "sessions" ? ["全部", "connected", "disconnected"] : ["全部", "执行中", "成功", "失败"];

  return <><div className="terminal-page-layer" inert={Boolean(detailSession || detailHistory || pending)} aria-hidden={detailSession || detailHistory || pending ? "true" : undefined}><ModulePageShell title={resolvePageMeta(page).title} subtitle={data.loading ? "正在连接 Controller 与 Agent" : `真实节点、受控任务与结果均来自后端 · 更新于 ${freshness(data.nodes, tasks, data.hostCollectedAt)}`} hideHeading page={page} className="terminal-page" viewContext={false} filters={<><ModuleSearch value={search} placeholder="搜索真实节点、命令或输出" onChange={setSearch} /><FieldSelect label={mode === "sessions" ? "Agent" : "结果"} value={filter} options={options} onChange={(value) => setFilters((current) => ({ ...current, [mode]: value }))} /></>} metrics={<><MetricTile icon={TerminalSquare} label="在线 Agent" value={`${sessions.filter((row) => row.status === "connected").length}`} tone="blue" /><MetricTile icon={Clock3} label="真实任务" value={`${history.length}`} tone="green" /><MetricTile icon={Shield} label="受控能力" value="1" tone="orange" /></>}>
    {data.loading && <span className="sr-only" role="status">正在从真实后端加载终端节点</span>}{data.error && <div className="overview-error-state"><Shield size={18} /><span>{data.error}</span><button type="button" disabled={data.loading} onClick={() => void data.retry()}>重试</button></div>}{!data.loading && !data.error && <p className="module-freshness-note"><Clock3 size={14} />后端更新于 {freshness(data.nodes, tasks, data.hostCollectedAt)}</p>}<div className={`terminal-workbench terminal-${mode}-view`}><section className="terminal-side-panel">{mode === "sessions" && <LiveSessionList rows={sessionRows} selectedId={selected?.id ?? ""} onSelect={(row) => setSelectedId(row.id)} onDetail={setDetailSessionId} />}{mode === "history" && <LiveHistoryList rows={historyRows} onDetail={setHistoryId} onCopy={(value) => copy(value, "命令已复制")} onRun={rerun} />}</section><LiveConsole session={selected} command={command} logs={logs} busy={submitting} canExecute={canExecute} commandSupported={!command.trim() || !commandCapability(command) || supportsCommand(selectedNode, command)} onCommand={setCommand} onRun={() => requestExecution(command)} onDetail={() => selected && setDetailSessionId(selected.id)} onCopy={() => copy(logs.join("\n"), "真实输出已复制")} /></div></ModulePageShell></div>
    {detailSession && <TerminalSessionDrawer session={detailSession} outputLineCount={history.filter((row) => row.nodeId === detailSession.id).length} onClose={() => setDetailSessionId(null)} />}{detailHistory && <DetailDrawer title="真实任务详情" subtitle={`${detailHistory.host} · ${detailHistory.time}`} className="terminal-history-drawer" modal onClose={() => setHistoryId(null)}><div className="terminal-history-detail"><section><h3>受控命令</h3><code>{detailHistory.command}</code></section><section><h3>Agent 返回</h3><pre>{detailHistory.output}</pre></section></div></DetailDrawer>}{pending && <ConfirmDialog className="terminal-command-confirm" title="确认执行受控命令" message="Controller 将校验权限与节点范围，并由 Agent 执行白名单只读命令。" detail={pending.command} confirmLabel={submitting ? "提交中..." : "确认执行"} tone="warning" confirmDisabled={!password || submitting} onClose={() => !submitting && setPending(null)} onConfirm={() => void submit()}><label className="terminal-reauth-field"><span><KeyRound size={15} />当前密码</span><input data-confirm-initial autoFocus type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{submitError && <p className="form-error" role="alert">{submitError}</p>}</ConfirmDialog>}</>;
}

export { TerminalPage };
